environment: prod
cloud: fmi

image:
  repository:
    host: quay.io/fmi/radon
    tag: latest

security:
  userId: 999
  groupId: 999
  sccGroup: restricted-v2-uid-999

storage:
  persistent:
    claim:
      name: radondb-pv-claim
  size: 128Mi
  storageClassName:
  volumeMode: Filesystem
  mountPath: /radondb

serviceAccount:
  create: true

imageStream: false

secrets:
  credentials: radon-credentials
  certificates: radon-ssl
  storePath:
