apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-mounting
  namespace: kube-system
  labels:
    app: secret-mounting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-mounting
  template:
    metadata:
      labels:
        app: secret-mounting
      annotations:
        eks.amazonaws.com/compute-type: ec2
    spec:
      serviceAccountName: geoweb-eks-secret-service-account
      containers:
      - name: secret-mounting
        image: busybox:latest
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        ports:
        - containerPort: 80
        volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aws-secrets"