{{- if .Values.secretProvider }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.opmet.spcName }}
spec:
  provider: {{ .Values.secretProvider }}
  parameters:
  {{- if or (eq .Values.secretProvider "aws") (eq .Values.secretProvider "azure") }}
    objects: |
    {{- if and .Values.opmet.db_secret (not .Values.opmet.db.useZalandoOperatorDb) }}
      - objectName: {{ .Values.opmet.db_secret | quote }}
        objectType: {{ .Values.opmet.db_secretType | quote }}
    {{- end }}
    {{- if .Values.opmet.ssh_secret }}
      - objectName: {{ .Values.opmet.ssh_secret | quote }}
        objectType: {{ .Values.opmet.ssh_secretType | quote }}
    {{- end }}
    {{- if .Values.opmet.ssh_passphrase_secret }}
      - objectName: {{ .Values.opmet.ssh_passphrase_secret | quote }}
        objectType: {{ .Values.opmet.ssh_passphrase_secretType | quote }}
    {{- end }}
  {{- else if eq .Values.secretProvider "gcp" }}
    secrets: |
    {{- if and .Values.opmet.db_secret (not .Values.opmet.db.useZalandoOperatorDb) }}
      - resourceName: {{ .Values.opmet.db_secret | quote }}
        path: {{ .Values.opmet.db_secretPath | quote }}
    {{- end }}
    {{- if .Values.opmet.ssh_secret }}
      - resourceName: {{ .Values.opmet.ssh_secret | quote }}
        path: {{ .Values.opmet.ssh_secretPath | quote }}
    {{- end }}
    {{- if .Values.opmet.ssh_passphrase_secret }}
      - resourceName: {{ .Values.opmet.ssh_passphrase_secret | quote }}
        path: {{ .Values.opmet.ssh_passphrase_secretPath | quote }}
    {{- end }}
  {{- else if eq .Values.secretProvider "vault" }}
    objects: |
    {{- if and .Values.opmet.db_secret (not .Values.opmet.db.useZalandoOperatorDb) }}
      - objectName: {{ .Values.opmet.db_secret | quote }}
        secretPath: {{ .Values.opmet.db_secretPath | quote }}
        secretKey: {{ .Values.opmet.db_secretKey | quote }}
    {{- end }}
    {{- if .Values.opmet.ssh_secret }}
      - objectName: {{ .Values.opmet.ssh_secret | quote }}
        secretPath: {{ .Values.opmet.ssh_secretPath | quote }}
        secretKey: {{ .Values.opmet.ssh_secretKey | quote }}
    {{- end }}
    {{- if .Values.opmet.ssh_passphrase_secret }}
      - objectName: {{ .Values.opmet.ssh_passphrase_secret | quote }}
        secretPath: {{ .Values.opmet.ssh_passphrase_secretPath | quote }}
        secretKey: {{ .Values.opmet.ssh_passphrase_secretKey | quote }}
    {{- end }}
  {{- end }}
  {{- range $key, $value := .Values.secretProviderParameters }}
    {{ $key }}: {{ $value }}
  {{- end }}
  secretObjects: # Creates kubernetes secret objects
  {{- if and .Values.opmet.db_secret (not .Values.opmet.db.useZalandoOperatorDb) }}
  - data:
    - key: OPMET_BACKEND_DB
      objectName: {{ .Values.opmet.db_secret }}
    secretName: {{ .Values.opmet.db_secretName }}
    type: Opaque
  {{- end }}
  {{- if .Values.opmet.ssh_secret }}
  - data:
    - key: ssh-privatekey
      objectName: {{ .Values.opmet.ssh_secret }}
    secretName: {{ .Values.opmet.ssh_secretName }}
    type: kubernetes.io/ssh-auth
  {{- end }}
  {{- if .Values.opmet.ssh_passphrase_secret }}
  - data:
    - key: SSH_KEY_PASSPHRASE
      objectName: {{ .Values.opmet.ssh_passphrase_secret }}
    secretName: {{ .Values.opmet.ssh_passphrase_secretName }}
    type: Opaque
  {{- end }}
{{- else }}
{{- if and .Values.opmet.db_secret (not .Values.opmet.db.useZalandoOperatorDb) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.opmet.db_secretName }}
data:
  OPMET_BACKEND_DB: {{ .Values.opmet.db_secret }}
{{- end }}
{{- if .Values.opmet.ssh_secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.opmet.ssh_passphrase_secretName }}
data:
  SSH_KEY_PASSPHRASE: {{ .Values.opmet.ssh_passphrase_secret }}
{{- end }}
{{- if .Values.opmet.ssh_passphrase_secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.opmet.ssh_secretName }}
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: {{ .Values.opmet.ssh_secret }}
{{- end }}
{{- end }}