apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.opmet.name }}
  annotations:
  {{- if .Values.opmet.commitHash }}
    commitHash: {{ .Values.opmet.commitHash }}
  {{- end }}
data:
  VERSION: {{ default .Chart.AppVersion .Values.versions.opmet | quote }}
{{- if .Values.opmet.env.MESSAGECONVERTER_URL }}
  MESSAGECONVERTER_URL: {{ .Values.opmet.env.MESSAGECONVERTER_URL | quote }}
{{- end }}
{{- if .Values.opmet.env.PUBLISHER_URL }}
  PUBLISHER_URL: {{ .Values.opmet.env.PUBLISHER_URL | quote }}
{{- end }}
{{- if .Values.opmet.env.OPMET_BACKEND_PORT_HTTP }}
  OPMET_BACKEND_PORT_HTTP: {{ .Values.opmet.env.OPMET_BACKEND_PORT_HTTP | quote }}
{{- end }}
{{- if .Values.opmet.env.BACKEND_CONFIG }}
  BACKEND_CONFIG: {{ .Values.opmet.env.BACKEND_CONFIG | quote }}
{{- end }}
{{- if .Values.opmet.env.SIGMET_CONFIG }}
  SIGMET_CONFIG: {{ .Values.opmet.env.SIGMET_CONFIG | quote }}
{{- end }}
{{- if .Values.opmet.env.AIRMET_CONFIG }}
  AIRMET_CONFIG: {{ .Values.opmet.env.AIRMET_CONFIG | quote }}
{{- end }}