apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.opmet.nginx.name }}
data:
{{- if .Values.opmet.nginx.OPMET_ENABLE_SSL }}
  OPMET_ENABLE_SSL: {{ .Values.opmet.nginx.OPMET_ENABLE_SSL | quote }}
{{- end }}
{{- if .Values.opmet.nginx.OAUTH2_USERINFO }}
  OAUTH2_USERINFO: {{ .Values.opmet.nginx.OAUTH2_USERINFO | quote }}
{{- end }}
{{- if .Values.opmet.nginx.OPMET_BACKEND_HOST }}
  OPMET_BACKEND_HOST: {{ .Values.opmet.nginx.OPMET_BACKEND_HOST | quote }}
{{- end }}
{{- if .Values.opmet.nginx.NGINX_PORT_HTTP }}
  NGINX_PORT_HTTP: {{ .Values.opmet.nginx.NGINX_PORT_HTTP | quote }}
{{- end }}
{{- if .Values.opmet.nginx.NGINX_PORT_HTTPS }}
  NGINX_PORT_HTTPS: {{ .Values.opmet.nginx.NGINX_PORT_HTTPS | quote }}
{{- end }}