{{- if .Values.frontend.secretProvider }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.opmet.secretServiceAccount }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.opmet.iamRoleARN }}
{{- end}}