apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.opmet.name }}
  annotations:
  {{- if .Values.opmet.commitHash }}
    commitHash: {{ .Values.opmet.commitHash }}
  {{- end }}
data:
  MESSAGECONVERTER_URL: {{ .Values.opmet.env.MESSAGECONVERTER_URL | quote }}
  OAUTH2_USERINFO: {{ .Values.opmet.env.OAUTH2_USERINFO | quote }}
  OPMET_BACKEND_PORT_HTTP: {{ .Values.opmet.env.OPMET_BACKEND_PORT_HTTP | quote }}
  EXTERNALADDRESSES: {{ .Values.opmet.env.EXTERNALADDRESSES | quote }}
  OPMET_ENABLE_SSL: {{ .Values.opmet.env.OPMET_ENABLE_SSL | quote }}
  FORWARDED_ALLOW_IPS: {{ .Values.opmet.env.FORWARDED_ALLOW_IPS | quote }}