apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.opmet.name }}
  labels:
    app: {{ .Values.opmet.name }}
spec:
  replicas: {{ .Values.opmet.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.opmet.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.opmet.name }}
      annotations:
        eks.amazonaws.com/compute-type: ec2
      {{- if .Values.opmet.commitHash }}
        commitHash: {{ .Values.opmet.commitHash }}
      {{- end }}
    spec:
    {{- if eq .Values.secretProvider "aws" }}
      serviceAccountName: {{ .Values.opmet.secretServiceAccount }}
    {{- end }}
      containers:
      - name: {{ .Values.opmet.name }}
        image: {{ .Values.opmet.registry }}:{{ .Values.versions.opmet }}
      {{- if .Values.opmet.imagePullPolicy }}
        imagePullPolicy: {{ .Values.opmet.imagePullPolicy }}
      {{- end }}
        ports:
        - containerPort: {{ .Values.opmet.env.OPMET_BACKEND_PORT_HTTP }}
        envFrom:
        - configMapRef:
            name: {{ .Values.opmet.name }}
        env:
        - name: SQLALCHEMY_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.opmet.db_secretName }}
              key: OPMET_BACKEND_DB
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        command: ["/bin/sh"]
        args: ["-c", "sleep 10 ; gunicorn --bind 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker --log-config opmet_logging.conf opmet_backend.main:app"]
      - name: {{ .Values.opmet.messageconverter.name }}
        image: {{ .Values.opmet.messageconverter.registry }}:{{ .Values.opmet.messageconverter.version }}
      {{- if .Values.opmet.imagePullPolicy }}
        imagePullPolicy: {{ .Values.opmet.imagePullPolicy }}
      {{- end }}
        ports:
        - containerPort: {{ .Values.opmet.messageconverter.port }}
        envFrom:
        - configMapRef:
            name: {{ .Values.opmet.name }}
      - name: {{ .Values.opmet.publisher.name }}
        image: {{ .Values.opmet.publisher.registry }}:{{ .Values.versions.opmet }}
      {{- if .Values.opmet.imagePullPolicy }}
        imagePullPolicy: {{ .Values.opmet.imagePullPolicy }}
      {{- end }}
        ports:
        - containerPort: {{ .Values.opmet.publisher.port }}
        envFrom:
        - configMapRef:
            name: {{ .Values.opmet.publisher.name }}
        volumeMounts:
        - name: publisher-volume
          mountPath: {{ .Values.opmet.publisher.DESTINATION | quote }}
      - name: {{ .Values.opmet.nginx.name }}
        image: {{ .Values.opmet.nginx.registry }}:{{ .Values.versions.opmet }}
      {{- if .Values.opmet.imagePullPolicy }}
        imagePullPolicy: {{ .Values.opmet.imagePullPolicy }}
      {{- end }}
        ports:
        - containerPort: {{ .Values.opmet.nginx.NGINX_PORT_HTTP }}
        envFrom:
        - configMapRef:
            name: {{ .Values.opmet.nginx.name }}
      volumes:
      - name: secrets-store-inline
      {{- if .Values.secretProvider }}
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .Values.opmet.spcName | quote }}
      {{- else }}
        secret:
          secretName: {{ .Values.opmet.db_secretName | quote }}
      {{- end }}
      - name: publisher-volume
      {{- if .Values.opmet.publisher.volumeOptions }}
        {{- toYaml .Values.opmet.publisher.volumeOptions | nindent 8 }}
      {{- else }}
        emptyDir:
      {{- end }}