{{- if .Values.secretProvider }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.opmet.spcName }}
spec:
  provider: {{ .Values.secretProvider }}
  parameters: # Fetches secrets from configured secretProvider
{{- if or (eq .Values.secretProvider "aws") (eq .Values.secretProvider "azure") (eq .Values.secretProvider "vault") }}
    objects: |
{{- else if eq .Values.secretProvider "gcp" }}
    secrets: |
{{- end }}
  {{- if and .Values.opmet.db_secret (not .Values.opmet.db.useZalandoOperatorDb) }}
    {{- if or (eq .Values.secretProvider "aws") (eq .Values.secretProvider "azure") }}
      - objectName: {{ .Values.opmet.db_secret | quote }}
        objectType: {{ .Values.opmet.db_secretType | quote }}
    {{- else if eq .Values.secretProvider "gcp" }}
      - resourceName: {{ .Values.opmet.db_secret | quote }}
        path: {{ .Values.opmet.db_secretPath | quote }}
    {{- else if eq .Values.secretProvider "vault" }}
      - objectName: {{ .Values.opmet.db_secret | quote }}
        secretPath: {{ .Values.opmet.db_secretPath | quote }}
        secretKey: {{ .Values.opmet.db_secretKey | quote }}
    {{- end }}
  {{- end }}
  {{- range $ssh_passphrase_secret := .Values.opmet.ssh_passphrase_secrets }}
    {{- if or (eq $.Values.secretProvider "aws") (eq $.Values.secretProvider "azure") }}
      - objectName: {{ $ssh_passphrase_secret.secret | quote }}
        objectType: {{ $ssh_passphrase_secret.type | quote }}
    {{- else if eq $.Values.secretProvider "gcp" }}
      - resourceName: {{ $ssh_passphrase_secret.secret | quote }}
        path: {{ $ssh_passphrase_secret.path | quote }}
    {{- else if eq $.Values.secretProvider "vault" }}
      - objectName: {{ $ssh_passphrase_secret.secret | quote }}
        secretPath: {{ $ssh_passphrase_secret.path | quote }}
        secretKey: {{ $ssh_passphrase_secret.key | quote }}
    {{- end }}
  {{- end}}
  {{- range $ssh_secret := .Values.opmet.ssh_secrets }}
    {{- if or (eq $.Values.secretProvider "aws") (eq $.Values.secretProvider "azure") }}
      - objectName: {{ $ssh_secret.secret | quote }}
        objectType: {{ $ssh_secret.type | quote }}
    {{- else if eq $.Values.secretProvider "gcp" }}
      - resourceName: {{ $ssh_secret.secret | quote }}
        path: {{ $ssh_secret.path | quote }}
    {{- else if eq $.Values.secretProvider "vault" }}
      - objectName: {{ $ssh_secret.secret | quote }}
        secretPath: {{ $ssh_secret.path | quote }}
        secretKey: {{ $ssh_secret.key | quote }}
    {{- end }}
  {{- end}}
  {{- range $key, $value := .Values.secretProviderParameters }}
    {{ $key }}: {{ $value }}
  {{- end }}
  secretObjects: # Creates kubernetes secret objects
  {{- if and .Values.opmet.db_secret (not .Values.opmet.db.useZalandoOperatorDb) }}
  - data:
    - key: OPMET_BACKEND_DB
      objectName: {{ .Values.opmet.db_secret }}
    secretName: {{ .Values.opmet.db_secretName }}
    type: Opaque
  {{- end }}
  {{- range $ssh_secret := .Values.opmet.ssh_secrets }}
  - data:
    - key: ssh-privatekey
      objectName: {{ $ssh_secret.secret }}
    secretName: {{ $ssh_secret.name }}
    type: kubernetes.io/ssh-auth
  {{- end }}
  {{- range $ssh_passphrase_secret := .Values.opmet.ssh_passphrase_secrets }}
  - data:
    - key: SSH_KEY_PASSPHRASE
      objectName: {{ $ssh_passphrase_secret.secret }}
    secretName: {{ $ssh_passphrase_secret.name }}
    type: Opaque
  {{- end }}
{{- else }}
{{- if and .Values.opmet.db_secret (not .Values.opmet.db.useZalandoOperatorDb) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.opmet.db_secretName }}
data:
  OPMET_BACKEND_DB: {{ .Values.opmet.db_secret }}
{{- end }}
{{- range $ssh_passphrase_secret := .Values.opmet.ssh_passphrase_secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $ssh_passphrase_secret.name }}
data:
  SSH_KEY_PASSPHRASE: {{ $ssh_passphrase_secret.secret }}
{{- end }}
{{- range $ssh_secret := .Values.opmet.ssh_secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $ssh_secret.name }}
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: {{ $ssh_secret.secret }}
{{- end }}
{{- end }}