versions:
  opmet: "v1.3.1"

opmet:
  name: opmet
  registry: registry.gitlab.com/opengeoweb/backend-services/opmet-backend/opmet-backend
  path: /opmet/(.*)
  svcPort: 80
  replicas: 1
  db_secret: cG9zdGdyZXNxbDovL2dlb3dlYjpwb3N0Z3Jlc0Bsb2NhbGhvc3Q6NTQzMi9vcG1ldA==
  db_secretName: opmet-db
  db_secretType: secretsmanager
  ssh_secretName: opmet-publisher-ssh-key
  ssh_secretType: secretsmanager
  ssh_passphrase_secretName: opmet-publisher-ssh-passphrase
  ssh_passphrase_secretType: secretsmanager
  spcName: opmet-spc
  secretServiceAccount: opmet-service-account
  resources:
    requests:
      memory: "150Mi"
      cpu: "50m"
    limits:
      memory: "300Mi"
      cpu: "1"
  livenessProbe:
    httpGet:
      path: /healthcheck
      port: 8000
    initialDelaySeconds: 60
    periodSeconds: 5
    failureThreshold: 5
  readinessProbe:
    httpGet:
      path: /healthcheck?readiness=true
      port: 8000
    initialDelaySeconds: 60
    periodSeconds: 5
    failureThreshold: 1
  env:
    MESSAGECONVERTER_URL: "http://localhost:8080"
    OPMET_BACKEND_PORT_HTTP: 8000
    EXTERNALADDRESSES: 0.0.0.0:80
    OPMET_ENABLE_SSL: "FALSE"
    FORWARDED_ALLOW_IPS: "*"
    PUBLISHER_URL: "http://localhost:8090/publish"
  messageconverter:
    name: opmet-messageconverter
    registry: registry.gitlab.com/opengeoweb/avi-msgconverter/geoweb-knmi-avi-messageservices
    version: "0.2.0"
    port: 8080
    resources:
      requests:
        memory: "250Mi"
        cpu: "50m"
      limits:
        memory: "500Mi"
        cpu: "1"
    livenessProbe:
      httpGet:
        path: /healthcheck
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 5
    readinessProbe:
      httpGet:
        path: /healthcheck?readiness=true
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 1
  publisher:
    name: opmet-publisher
    registry: registry.gitlab.com/opengeoweb/backend-services/opmet-backend/opmet-backend-publisher-local
    port: 8090
    DESTINATION: /app/output
    PRIVATE_KEY_BASE_PATH: /mnt/secrets-store/
    resources:
      requests:
        memory: "50Mi"
        cpu: "50m"
      limits:
        memory: "100Mi"
        cpu: "1"
    livenessProbe:
      httpGet:
        path: /healthcheck
        port: 8090
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 5
    readinessProbe:
      httpGet:
        path: /healthcheck?readiness=true
        port: 8090
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 1
  nginx:
    name: opmet-nginx
    registry: registry.gitlab.com/opengeoweb/backend-services/opmet-backend/nginx-opmet-backend
    OPMET_ENABLE_SSL: "FALSE"
    NGINX_PORT_HTTP: 80
    EXTERNAL_HOSTNAME: localhost:80
    OPMET_BACKEND_HOST: localhost:8000
    resources:
      requests:
        memory: "10Mi"
        cpu: "10m"
      limits:
        memory: "100Mi"
        cpu: "100m"
    livenessProbe:
      httpGet:
        path: /health_check
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 5
    readinessProbe:
      httpGet:
        path: /health_check?readiness=true
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 1
  db:
    enableDefaultDb: true
    useZalandoOperatorDb: false
    name: opmet-db
    image: postgres
    port: 5432
    POSTGRES_DB: opmet
    POSTGRES_USER: geoweb
    POSTGRES_PASSWORD: postgres
    POSTGRES_VERSION: 15
    numberOfInstances: 1
    instanceSize: 100Mi
    zalandoTeamId: geoweb
    enableLogicalBackup: true
    cleanInstall: true
    backupTimestamp: "2030-01-01T00:00:00+00:00"
  useCustomConfigurationFiles: false
  customConfigurationLocation: local
  customConfigurationMountPath: /app/configuration_files/custom
  volumeAccessMode: ReadOnlyMany
  volumeSize: 100Mi

ingress:
  name: nginx-ingress-controller
  ingressClassName: nginx
