apiVersion: v1
kind: Service
metadata:
  name: {{ include "fmi-redis.fullname" . }}
  labels:
    app: {{ include "fmi-redis.fullname" . }}
spec:
  selector:
    app: {{ include "fmi-redis.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
      name: redis
