apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.frontend.name }}
  annotations:
  {{- if .Values.frontend.commitHash }}
    commitHash: {{ .Values.frontend.commitHash }}
  {{- end }}
data:
{{- if .Values.frontend.env.GW_AUTH_LOGOUT_URL }}
  GW_AUTH_LOGOUT_URL: {{ .Values.frontend.env.GW_AUTH_LOGOUT_URL | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_AUTH_TOKEN_URL }}
  GW_AUTH_TOKEN_URL: {{ .Values.frontend.env.GW_AUTH_TOKEN_URL | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_AUTH_LOGIN_URL }}
  GW_AUTH_LOGIN_URL: {{ .Values.frontend.env.GW_AUTH_LOGIN_URL | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_AUTH_ROLE_CLAIM_NAME }}
  GW_AUTH_ROLE_CLAIM_NAME: {{ .Values.frontend.env.GW_AUTH_ROLE_CLAIM_NAME | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_AUTH_ROLE_CLAIM_VALUE_PRESETS_ADMIN }}
  GW_AUTH_ROLE_CLAIM_VALUE_PRESETS_ADMIN: {{ .Values.frontend.env.GW_AUTH_ROLE_CLAIM_VALUE_PRESETS_ADMIN | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_CAP_BASE_URL }}
  GW_CAP_BASE_URL: {{ .Values.frontend.env.GW_CAP_BASE_URL | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_DRAWINGS_BASE_URL }}
  GW_DRAWINGS_BASE_URL: {{ .Values.frontend.env.GW_DRAWINGS_BASE_URL | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_APP_URL }}
  GW_APP_URL: {{ .Values.frontend.env.GW_APP_URL | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_INITIAL_PRESETS_FILENAME }}
  GW_INITIAL_PRESETS_FILENAME: {{ .Values.frontend.env.GW_INITIAL_PRESETS_FILENAME | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_CAP_CONFIGURATION_FILENAME }}
  GW_CAP_CONFIGURATION_FILENAME: {{ .Values.frontend.env.GW_CAP_CONFIGURATION_FILENAME | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_TIMESERIES_CONFIGURATION_FILENAME }}
  GW_TIMESERIES_CONFIGURATION_FILENAME: {{ .Values.frontend.env.GW_TIMESERIES_CONFIGURATION_FILENAME | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_DEFAULT_THEME }}
  GW_DEFAULT_THEME: {{ .Values.frontend.env.GW_DEFAULT_THEME | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_FEATURE_APP_TITLE }}
  GW_FEATURE_APP_TITLE: {{ .Values.frontend.env.GW_FEATURE_APP_TITLE | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_FEATURE_FORCE_AUTHENTICATION }}
  GW_FEATURE_FORCE_AUTHENTICATION: {{ .Values.frontend.env.GW_FEATURE_FORCE_AUTHENTICATION | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_FEATURE_MODULE_SPACE_WEATHER }}
  GW_FEATURE_MODULE_SPACE_WEATHER: {{ .Values.frontend.env.GW_FEATURE_MODULE_SPACE_WEATHER | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_TAF_BASE_URL }}
  GW_TAF_BASE_URL: {{ .Values.frontend.env.GW_TAF_BASE_URL | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_SW_BASE_URL }}
  GW_SW_BASE_URL: {{ .Values.frontend.env.GW_SW_BASE_URL | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_FEATURE_MENU_FEEDBACK }}
  GW_FEATURE_MENU_FEEDBACK: {{ .Values.frontend.env.GW_FEATURE_MENU_FEEDBACK | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_FEATURE_MENU_INFO }}
  GW_FEATURE_MENU_INFO: {{ .Values.frontend.env.GW_FEATURE_MENU_INFO | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_FEATURE_MENU_VERSION }}
  GW_FEATURE_MENU_VERSION: {{ .Values.frontend.env.GW_FEATURE_MENU_VERSION | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_FEATURE_MENU_FE_VERSION }}
  GW_FEATURE_MENU_FE_VERSION: {{ .Values.frontend.env.GW_FEATURE_MENU_FE_VERSION | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_FEATURE_INITIALIZE_SENTRY }}
  GW_FEATURE_INITIALIZE_SENTRY: {{ .Values.frontend.env.GW_FEATURE_INITIALIZE_SENTRY | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_PRESET_BACKEND_URL }}
  GW_PRESET_BACKEND_URL: {{ .Values.frontend.env.GW_PRESET_BACKEND_URL | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_FEATURE_MENU_USER_DOCUMENTATION_URL }}
  GW_FEATURE_MENU_USER_DOCUMENTATION_URL: {{ .Values.frontend.env.GW_FEATURE_MENU_USER_DOCUMENTATION_URL | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_SIGMET_BASE_URL }}
  GW_SIGMET_BASE_URL: {{ .Values.frontend.env.GW_SIGMET_BASE_URL | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_AIRMET_BASE_URL }}
  GW_AIRMET_BASE_URL: {{ .Values.frontend.env.GW_AIRMET_BASE_URL | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_FEATURE_MODULE_SIGMET_CONFIGURATION }}
  GW_FEATURE_MODULE_SIGMET_CONFIGURATION: {{ .Values.frontend.env.GW_FEATURE_MODULE_SIGMET_CONFIGURATION | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_FEATURE_MODULE_AIRMET_CONFIGURATION }}
  GW_FEATURE_MODULE_AIRMET_CONFIGURATION: {{ .Values.frontend.env.GW_FEATURE_MODULE_AIRMET_CONFIGURATION | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_LANGUAGE }}
  GW_LANGUAGE: {{ .Values.frontend.env.GW_LANGUAGE | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_FEATURE_DISPLAY_SEARCH_ON_MAP }}
  GW_FEATURE_DISPLAY_SEARCH_ON_MAP: {{ .Values.frontend.env.GW_FEATURE_DISPLAY_SEARCH_ON_MAP | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_VERSION_PROGRESS_NOTES_URL }}
  GW_VERSION_PROGRESS_NOTES_URL: {{ .Values.frontend.env.GW_VERSION_PROGRESS_NOTES_URL | quote }}
{{- end }}
{{- if .Values.frontend.env.GW_TECHNICAL_RELEASE_NOTES_URL }}
  GW_TECHNICAL_RELEASE_NOTES_URL: {{ .Values.frontend.env.GW_TECHNICAL_RELEASE_NOTES_URL | quote }}
{{- end }}
