apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}-{{ .Values.frontend.name }}
  annotations:
  {{- if .Values.ingress.customAnnotations }}
    {{- with .Values.ingress.customAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- else }}
  {{- if .Values.frontend.auth_secret }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ .Values.frontend.auth_secretName }}
  {{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET"
  {{- if .Values.ingress.serverSnippet }}
      nginx.ingress.kubernetes.io/server-snippet: |
      {{ .Values.ingress.serverSnippet | nindent 6 }}
  {{- end }}
  {{- if .Values.ingress.rules }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
    {{- .Values.ingress.rules | nindent 6 }}
  {{- end }}
  {{- end }}
spec:
{{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
{{- end }}
  rules:
    - host: {{ .Values.frontend.url }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontend.name }}
                port:
                  number: {{ .Values.frontend.svcPort }}