apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.frontend.spcName }}
spec:
  provider: aws
  parameters:
    region: eu-north-1
    objects: |
        - objectName: {{ .Values.frontend.client_id_secret | quote }}
          objectType: "secretsmanager"
{{ if .Values.frontend.auth_secret }}
        - objectName: {{ .Values.frontend.auth_secret | quote }}
          objectType: "secretsmanager"
{{ end }}
  secretObjects: # Creates kubernetes secret objects
  - data:
    - key: GW_AUTH_CLIENT_ID
      objectName: {{ .Values.frontend.client_id_secret }}
    secretName: {{ .Values.frontend.idSecretName }}
    type: Opaque
{{ if .Values.frontend.auth_secret }}
  - data:
    - key: auth
      objectName: {{ .Values.frontend.auth_secret }}
    secretName: {{ .Values.frontend.auth_secret }}
    type: Opaque
{{ end }}