{{- if .Values.secretProvider }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.frontend.spcName }}
spec:
  provider: {{ .Values.secretProvider }}
  parameters:
  {{- if eq .Values.secretProvider "aws" }}
    objects: |
    {{- if .Values.frontend.client_id_secret }}
      - objectName: {{ .Values.frontend.client_id_secret | quote }}
        objectType: {{ .Values.frontend.client_id_secretType | quote }}
    {{- end }}
    {{- if .Values.frontend.auth_secret }}
      - objectName: {{ .Values.frontend.auth_secret | quote }}
        objectType: {{ .Values.frontend.auth_secretType | quote }}
    {{- end }}
  {{- else if eq .Values.secretProvider "azure" }}
    objects: |
      array:
        - |
        {{- if .Values.frontend.client_id_secret }}
          objectName: {{ .Values.frontend.client_id_secret | quote }}
          objectType: {{ .Values.frontend.client_id_secretType | quote }}
        {{- end }}
        {{- if .Values.frontend.auth_secret }}
        - |
          objectName: {{ .Values.frontend.auth_secret | quote }}
          objectType: {{ .Values.frontend.auth_secretType | quote }}
        {{- end }}
  {{- else if eq .Values.secretProvider "gcp" }}
    secrets: |
    {{- if .Values.frontend.client_id_secret }}
      - resourceName: {{ .Values.frontend.client_id_secret | quote }}
        path: {{ .Values.frontend.client_id_secretPath | quote }}
    {{- end }}
    {{- if .Values.frontend.auth_secret }}
      - resourceName: {{ .Values.frontend.auth_secret | quote }}
        path: {{ .Values.frontend.auth_secretType | quote }}
    {{- end }}
  {{- else if eq .Values.secretProvider "vault" }}
    objects: |
    {{- if .Values.frontend.client_id_secret }}
      - objectName: {{ .Values.frontend.client_id_secret | quote }}
        secretPath: {{ .Values.frontend.client_id_secretPath | quote }}
        secretKey: {{ .Values.frontend.client_id_secretKey | quote }}
    {{- end }}
    {{- if .Values.frontend.auth_secret }}
      - objectName: {{ .Values.frontend.auth_secret | quote }}
        secretPath: {{ .Values.frontend.auth_secretPath | quote }}
        secretKey: {{ .Values.frontend.auth_secretKey | quote }}
    {{- end }}
  {{- end }}
  {{- range $key, $value := .Values.secretProviderParameters }}
    {{ $key }}: {{ $value }}
  {{- end }}
  secretObjects: # Creates kubernetes secret objects
{{- if .Values.frontend.client_id_secret }}
  - data:
    - key: GW_AUTH_CLIENT_ID
      objectName: {{ .Values.frontend.client_id_secret }}
    secretName: {{ .Values.frontend.client_id_secretName }}
    type: Opaque
{{- end }}
{{- if .Values.frontend.auth_secret }}
  - data:
    - key: auth
      objectName: {{ .Values.frontend.auth_secret }}
    secretName: {{ .Values.frontend.auth_secretName }}
    type: Opaque
{{- end }}
{{- else }}
{{- if .Values.frontend.client_id_secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.frontend.client_id_secretName }}
data:
  GW_AUTH_CLIENT_ID: {{ .Values.frontend.client_id_secret }}
{{- end }}
{{- if .Values.frontend.auth_secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.frontend.auth_secretName }}
data:
  auth: {{ .Values.frontend.auth_secret }}
{{- end }}
{{- end }}
