{{- if .Values.frontend.useSecretProvider }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.frontend.spcName }}
spec:
  provider: aws
  parameters:
    region: eu-north-1
    objects: |
        - objectName: {{ .Values.frontend.client_id_secret | quote }}
          objectType: "secretsmanager"
{{- if .Values.frontend.auth_secret }}
        - objectName: {{ .Values.frontend.auth_secret | quote }}
          objectType: "secretsmanager"
{{- end }}
  secretObjects: # Creates kubernetes secret objects
  - data:
    - key: GW_AUTH_CLIENT_ID
      objectName: {{ .Values.frontend.client_id_secret }}
    secretName: {{ .Values.frontend.idSecretName }}
    type: Opaque
{{- if .Values.frontend.auth_secret }}
  - data:
    - key: auth
      objectName: {{ .Values.frontend.auth_secret }}
    secretName: {{ .Values.frontend.auth_secret }}
    type: Opaque
{{- end }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.frontend.idSecretName }}
data:
  GW_AUTH_CLIENT_ID: {{ .Values.frontend.client_id_secret }}
{{- if .Values.frontend.auth_secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.frontend.auth_secret }}
data:
  auth: {{ .Values.frontend.auth_secret }}
{{- end }}
{{- end }}
