apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.frontend.spcName }}
spec:
  provider: aws
  parameters:
    region: eu-north-1
    objects: |
        - objectName: {{ .Values.frontend.db_secret | quote }}
          objectType: "secretsmanager"
  secretObjects: # Creates kubernetes secret objects
  - data:
    - key: GW_AUTH_CLIENT_ID
      objectName: {{ .Values.frontend.db_secret }}
    secretName: {{ .Values.frontend.secretName }}
    type: Opaque