apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.frontend.name }}
  annotations:
  {{- if .Values.frontend.commitHash }}
    commitHash: {{ .Values.frontend.commitHash }}
  {{- end }}
data:
  {{- range $key, $value := .Values.frontend.env }}
  {{ $key | upper }}: {{ $value | quote }}
  {{- end }}
  {{- if .Values.frontend.customConfiguration.enabled }}
  {{- range $filename, $content := .Values.frontend.customConfiguration.files }}
  {{ $filename }}: {{ $content | toJson | quote }}
  {{- end }}
  {{- end }}  