{{- if eq (default "none" .Values.frontend.runtimeConfiguration.source) "inline" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.frontend.name }}-runtime-config
data:
{{- range $filename, $content := .Values.frontend.runtimeConfiguration.files }}
  {{ $filename | quote }}: {{ $content | toJson | quote }}
{{- end }}
{{- end }}
