apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.location.name }}
  annotations:
  {{- if .Values.location.commitHash }}
    commitHash: {{ .Values.location.commitHash }}
  {{- end }}
data:
  {{- range $key, $value := .Values.location.env }}
  {{ $key | upper }}: {{ $value | quote }}
  {{- end }}