apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.sftp.pvcName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sftp-puller.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  {{- if .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  {{- end }}
