{{ if eq .Values.cloud "aws" -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.secrets.credentials }}
        objectType: secretsmanager
        jmesPath:
          - path: POSTGRES_PASSWORD
            objectAlias: postgres
          - path: RADON_RADON_ADMIN_PASSWORD
            objectAlias: radonAdmin
          - path: RADON_WETODB_PASSWORD
            objectAlias: wetodb
          - path: RADON_RADON_CLIENT_PASSWORD
            objectAlias: radonClient
      - objectName: {{ .Values.secrets.certificates }}
        objectType: secretsmanager
  secretObjects: # map secrets from aws secret storage to kubernetes secrets
  - data:
    - key: POSTGRES_PASSWORD
      objectName: postgres
    - key: RADON_RADON_ADMIN_PASSWORD
      objectName: radonAdmin
    - key: RADON_WETODB_PASSWORD
      objectName: wetodb
    - key: RADON_RADON_CLIENT_PASSWORD
      objectName: radonClient
    secretName: {{ .Values.secrets.credentials }}
    type: Opaque
{{- end }}
