apiVersion: v1
data:
  POSTGRES_PASSWORD: pass
  RADON_RADON_ADMIN_PASSWORD: pass
  RADON_RADONCLIENT_PASSWORD: pass
  RADON_WETODB_PASSWORD: pass
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Release.Name }}
type: Opaque
