{{ if eq .Values.cloud "fmi" -}}
apiVersion: v1
data:
  POSTGRES_PASSWORD: pass
  RADON_RADON_ADMIN_PASSWORD: pass
  RADON_RADONCLIENT_PASSWORD: pass
  RADON_WETODB_PASSWORD: pass
kind: Secret
metadata:
  name: radon-credentials
  namespace: {{ .Release.Name }}
type: Opaque
---
apiVersion: v1
data:
  server.crt: pass
  server.key: pass
kind: Secret
metadata:
  name: radon-ssl
  namespace: {{ .Release.Name }}
type: Opaque
{{- end }}
