apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "radon.fullname" . }}
  labels:
    app: {{ .Release.Name }}
{{ include "radon.labels" . | indent 4 }}
spec:
  serviceName: {{ .Release.Name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      {{ if eq .Values.cloud "aws" }}
      annotations:
        openshift.io/required-scc: {{ .Values.security.sccGroup }}
      {{ end }}
    spec:
      securityContext:
        runAsUser: {{ .Values.security.userId }}
        runAsGroup: {{ .Values.security.groupId }}
        fsGroup: {{ .Values.security.userId }}
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: radondb
          {{- if .Values.imageStream }}
          image: "{{ include "radon.localImageRepository" . }}/{{ .Release.Name }}:{{ .Values.image.repository.tag }}"
          {{ else }}
          image: {{ .Values.image.repository.host }}:{{ .Values.image.repository.tag }}
          {{ end -}}
          ports:
            - containerPort: 5432
          args: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
          env:
            - name: PGDATA
              value: {{ .Values.storage.mountPath }}/data
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD
            - name: RADON_RADON_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: RADON_RADON_ADMIN_PASSWORD
            - name: RADON_WETODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: RADON_WETODB_PASSWORD
            - name: RADON_RADONCLIENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: RADON_RADONCLIENT_PASSWORD
          volumeMounts:
            - mountPath: {{ .Values.storage.mountPath }}
              name: radondb
              readOnly: false
            - name: custom-config
              mountPath: /etc/postgresql
            - name: radon-ssl
              mountPath: /etc/postgresql/ssl
              readOnly: true
      volumes:
        - name: radondb
          persistentVolumeClaim:
            claimName: {{ .Values.storage.persistent.claim.name }}-{{ .Values.environment }}
        - name: custom-config
          configMap:
            name: custom-postgresql-config
        - name: radon-ssl
          secret:
            secretName: radon-ssl
            defaultMode: 0600
