apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.warnings.name }}
  labels:
    app: {{ .Values.warnings.name }}
spec:
  replicas: {{ .Values.warnings.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.warnings.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.warnings.name }}
      annotations:
        eks.amazonaws.com/compute-type: ec2
      {{- if .Values.warnings.commitHash }}
        commitHash: {{ .Values.warnings.commitHash }}
      {{- end }}
    spec:
    {{- if eq .Values.secretProvider "aws" }}
      serviceAccountName: {{ .Values.warnings.secretServiceAccount }}
    {{- end }}
      containers:
      - name: {{ .Values.warnings.name }}
        image: {{ .Values.warnings.registry }}:{{ default .Chart.AppVersion .Values.versions.warnings }}
      {{- if .Values.warnings.imagePullPolicy }}
        imagePullPolicy: {{ .Values.warnings.imagePullPolicy }}
      {{- end }}
      {{- if .Values.warnings.postStartCommand }}
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", {{ .Values.warnings.postStartCommand | quote }}]
      {{- end }}
        ports:
        - containerPort: {{ .Values.warnings.WARNINGS_PORT_HTTP }}
      {{- if .Values.warnings.resources }}
        resources: {{ toYaml .Values.warnings.resources | nindent 10 }}
      {{- end }}
      {{- if .Values.warnings.livenessProbe }}
        livenessProbe: {{ toYaml .Values.warnings.livenessProbe | nindent 10 }}
      {{- end }}
      {{- if .Values.warnings.readinessProbe }}
        readinessProbe: {{ toYaml .Values.warnings.readinessProbe | nindent 10 }}
      {{- end }}
        envFrom:
        - configMapRef:
            name: {{ .Values.warnings.name }}
        env:
      {{- if .Values.warnings.db.useZalandoOperatorDb }}
        - name: PG_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.warnings.db.POSTGRES_USER }}.{{ .Values.warnings.db.name }}.credentials.postgresql.acid.zalan.do
              key: password
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.warnings.db.POSTGRES_USER }}.{{ .Values.warnings.db.name }}.credentials.postgresql.acid.zalan.do
              key: username
      {{- end }}
        - name: WARNINGS_BACKEND_DB
        {{- if .Values.warnings.db.useZalandoOperatorDb }}
          value: "postgresql://$(PG_USER):$(PG_PASS)@{{ .Values.warnings.db.name }}:5432/{{ .Values.warnings.db.POSTGRES_DB }}"
        {{- else }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.warnings.db_secretName }}
              key: WARNINGS_BACKEND_DB
      {{- if not .Values.warnings.db.useZalandoOperatorDb }}
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      {{- end }}
      - name: {{ .Values.warnings.nginx.name }}
        image: {{ .Values.warnings.nginx.registry }}:{{ default .Chart.AppVersion .Values.versions.warnings }}
      {{- if .Values.warnings.imagePullPolicy }}
        imagePullPolicy: {{ .Values.warnings.imagePullPolicy }}
      {{- end }}
        ports:
        - containerPort: {{ .Values.warnings.nginx.NGINX_PORT_HTTP }}
      {{- if .Values.warnings.nginx.resources }}
        resources: {{ toYaml .Values.warnings.nginx.resources | nindent 10 }}
      {{- end }}
      {{- if .Values.warnings.nginx.livenessProbe }}
        livenessProbe: {{ toYaml .Values.warnings.nginx.livenessProbe | nindent 10 }}
      {{- end }}
      {{- if .Values.warnings.nginx.readinessProbe }}
        readinessProbe: {{ toYaml .Values.warnings.nginx.readinessProbe | nindent 10 }}
      {{- end }}
        envFrom:
        - configMapRef:
            name: {{ .Values.warnings.nginx.name }}
      {{- if .Values.warnings.db.enableDefaultDb }}
      - name: {{ .Values.warnings.db.name }}
        image: {{ .Values.warnings.db.image }}
        ports:
          - containerPort: {{ .Values.warnings.db.port }}
        env:
          - name: POSTGRES_DB
            value: {{ .Values.warnings.db.POSTGRES_DB }}
          - name: POSTGRES_USER
            value: {{ .Values.warnings.db.POSTGRES_USER }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.warnings.db.POSTGRES_PASSWORD }}
      {{- end }}
      volumes:
    {{- if not .Values.warnings.db.useZalandoOperatorDb }}
      - name: secrets-store-inline
      {{- if .Values.secretProvider }}
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .Values.warnings.spcName | quote }}
      {{- else }}
        secret:
          secretName: {{ .Values.warnings.db_secretName | quote }}
      {{- end }}
    {{- end }}