apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.warnings.name }}
spec:
  selector:
    app: {{ .Values.warnings.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.warnings.svcPort }}
      targetPort: {{ .Values.warnings.nginx.NGINX_PORT_HTTP }}