{{- if eq .Values.secretProvider "aws" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.warnings.secretServiceAccount }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.warnings.iamRoleARN }}
{{- end}}