apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.warnings.name }}
  annotations:
  {{- if .Values.warnings.commitHash }}
    commitHash: {{ .Values.warnings.commitHash }}
  {{- end }}
data:
  VERSION: {{ default .Chart.AppVersion .Values.versions.warnings | quote }}
  {{- range $key, $value := .Values.warnings.env }}
  {{ $key | upper }}: {{ $value | quote }}
  {{- end }}