{{- if .Values.secretProvider }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.warnings.spcName }}
spec:
  provider: {{ .Values.secretProvider }}
  parameters:
  {{- if or (eq .Values.secretProvider "aws") (eq .Values.secretProvider "azure") }}
    objects: |
      - objectName: {{ .Values.warnings.db_secret | quote }}
        objectType: {{ .Values.warnings.db_secretType | quote }}
  {{- else if eq .Values.secretProvider "gcp" }}
    secrets: |
      - resourceName: {{ .Values.warnings.db_secret | quote }}
        path: {{ .Values.warnings.db_secretPath | quote }}
  {{- else if eq .Values.secretProvider "vault" }}
    objects: |
      - objectName: {{ .Values.warnings.db_secret | quote }}
        secretPath: {{ .Values.warnings.db_secretPath | quote }}
        secretKey: {{ .Values.warnings.db_secretKey | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secretProviderParameters }}
    {{ $key }}: {{ $value }}
  {{- end }}
  secretObjects: # Creates kubernetes secret objects
  - data:
    - key: WARNINGS_BACKEND_DB
      objectName: {{ .Values.warnings.db_secret }}
    secretName: {{ .Values.warnings.db_secretName }}
    type: Opaque
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.warnings.db_secretName }}
data:
  WARNINGS_BACKEND_DB: {{ .Values.warnings.db_secret }}
{{- end}}