apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.warnings.name }}
  annotations:
  {{- if .Values.warnings.commitHash }}
    commitHash: {{ .Values.warnings.commitHash }}
  {{- end }}
data:
  VERSION: {{ default .Chart.AppVersion .Values.versions.warnings | quote }}
{{- if .Values.warnings.WARNINGS_PORT_HTTP }}
  WARNINGS_PORT_HTTP: {{ .Values.warnings.WARNINGS_PORT_HTTP | quote }}
{{- end }}