versions:
  warnings: "0.2.0"

warnings:
  name: warnings
  registry: registry.gitlab.com/opengeoweb/backend-services/warnings-backend/warnings-backend
  path: /warnings/(.*)
  svcPort: 80
  replicas: 1
  WARNINGS_PORT_HTTP: 8080
  postStartCommand: bin/admin.sh
  db_secret: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQGxvY2FsaG9zdDo1NDMyL3dhcm5pbmdz
  db_secretName: warnings-db
  db_secretType: secretsmanager
  spcName: warnings-spc
  secretServiceAccount: warnings-service-account
  resources:
    requests:
      memory: "250Mi"
      cpu: "50m"
    limits:
      memory: "400Mi"
      cpu: "1"
  livenessProbe:
    httpGet:
      path: /healthcheck
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 5
    failureThreshold: 5
  readinessProbe:
    httpGet:
      path: /healthcheck?readiness=true
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 5
    failureThreshold: 1
  nginx:
    name: warnings-nginx
    registry: registry.gitlab.com/opengeoweb/backend-services/warnings-backend/nginx-warnings-backend
    WARNINGS_ENABLE_SSL: "FALSE"
    WARNINGS_BACKEND_HOST: 0.0.0.0:8080
    NGINX_PORT_HTTP: 80
    NGINX_PORT_HTTPS: 443
    resources:
      requests:
        memory: "10Mi"
        cpu: "10m"
      limits:
        memory: "100Mi"
        cpu: "100m"
    livenessProbe:
      httpGet:
        path: /health_check
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 5
    readinessProbe:
      httpGet:
        path: /health_check?readiness=true
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 1
  db:
    enableDefaultDb: true
    name: postgres
    image: postgres
    port: 5432
    POSTGRES_DB: warnings
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres

ingress:
  name: nginx-ingress-controller
  ingressClassName: nginx
