versions:
  warnings:

warnings:
  name: warnings
  registry: registry.gitlab.com/opengeoweb/backend-services/warnings-backend/warnings-backend
  path: /warnings-backend/(.*)
  svcPort: 80
  replicas: 1
  minPodsAvailable: 0
  db_secret: cG9zdGdyZXNxbDovL2dlb3dlYjpwb3N0Z3Jlc0Bsb2NhbGhvc3Q6NTQzMi93YXJuaW5ncw==
  db_secretName: warnings-db
  db_secretType: secretsmanager
  spcName: warnings-spc
  secretServiceAccount: warnings-service-account
  resources:
    requests:
      memory: "512Mi"
      cpu: "15m"
    limits:
      memory: "1024Mi"
      cpu: "1"
  startupProbe:
    httpGet:
      path: /healthcheck?startup=true
      port: 8080
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 24  # Allow 4 minutes for startup
  livenessProbe:
    httpGet:
      path: /
      port: 8080
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 2
  readinessProbe:
    httpGet:
      path: /healthcheck?readiness=true
      port: 8080
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 1
  env:
    WARNINGS_PORT_HTTP: 8080
    APPLICATION_ROOT_PATH: /warnings-backend
  nginx:
    name: warnings-nginx
    registry: registry.gitlab.com/opengeoweb/backend-services/auth-backend/auth-backend
    version: "v0.6.0"
    ENABLE_SSL: "FALSE"
    BACKEND_HOST: 0.0.0.0:8080
    NGINX_PORT_HTTP: 80
    NGINX_PORT_HTTPS: 443
    ENV_VAR_STRICT_MODE: "FALSE"
    resources:
      requests:
        memory: "16Mi"
        cpu: "5m"
      limits:
        memory: "32Mi"
        cpu: "1"
    startupProbe:
      httpGet:
        path: /health_check?startup=true
        port: 80
      periodSeconds: 5
      timeoutSeconds: 5
      failureThreshold: 12  # Allow a minute for startup
    livenessProbe:
      httpGet:
        path: /health_check
        port: 80
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 2
    readinessProbe:
      httpGet:
        path: /health_check?readiness=true
        port: 80
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 1
  db:
    enableDefaultDb: true
    useZalandoOperatorDb: false
    name: warnings-db
    image: postgres
    port: 5432
    POSTGRES_DB: warnings
    POSTGRES_USER: geoweb
    POSTGRES_PASSWORD: postgres
    POSTGRES_VERSION: 15
    numberOfInstances: 1
    instanceSize: 100Mi
    zalandoTeamId: geoweb
    enableLogicalBackup: true
    cleanInstall: true
    backupTimestamp: "2030-01-01T00:00:00+00:00"
  useCustomConfigurationFiles: false
  customConfigurationLocation: local
  volumeAccessMode: ReadOnlyMany
  volumeSize: 100Mi

ingress:
  name: nginx-ingress-controller
  ingressClassName: nginx
