versions:
  frontend:

frontend:
  name: geoweb
  registry: registry.gitlab.com/opengeoweb/opengeoweb
  svcPort: 80
  containerPort: 8080
  replicas: 1
  auth_secretName: geoweb-auth
  auth_secretType: secretsmanager
  client_id_secretName: geoweb-client-id
  client_id_secretType: secretsmanager
  spcName: geoweb-spc
  secretServiceAccount: geoweb-service-account
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "1"
  livenessProbe:
    httpGet:
      path: /assets/config.json
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5
    failureThreshold: 5
  readinessProbe:
    httpGet:
      path: /assets/config.json?readiness=true
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5
    failureThreshold: 1
  env:
    GW_AUTH_LOGOUT_URL: "{app_url}"
    GW_AUTH_TOKEN_URL: https://gitlab.com/oauth/token
    GW_AUTH_LOGIN_URL: https://gitlab.com/oauth/authorize?client_id={client_id}&response_type=code&scope=email+openid+read_repository+read_api&redirect_uri={app_url}/code&state={state}&code_challenge={code_challenge}&code_challenge_method=S256
    GW_INFRA_BASE_URL: https://api.opengeoweb.com
    GW_FEATURE_FORCE_AUTHENTICATION: false
    GW_FEATURE_MODULE_SPACE_WEATHER: false
    GW_FEATURE_MENU_FEEDBACK: false
    GW_FEATURE_MENU_INFO: true
    GW_FEATURE_MENU_VERSION: false
    GW_FEATURE_MENU_FE_VERSION: true
  useCustomConfigurationFiles: false
  customConfigurationLocation: local
  customConfigurationMountPath: /usr/share/nginx/html/assets/custom
  volumeAccessMode: ReadOnlyMany
  volumeSize: 100Mi

ingress:
  name: nginx-ingress-controller
  rules: |
    if ($request_uri ~* \.(js)) {
      add_header "Document-Policy", "js-profiling";
    }
    if ($request_uri ~* \.(json)) {
      add_header Cache-Control "no-cache";
    }
    if ($request_uri ~* \.(woff2|svg)) {
      add_header Cache-Control "max-age=604800";
    }
    if ($request_uri ~* \.(webmanifest)) {
      more_clear_headers 'Content-Type';
      add_header Content-Type "application/manifest+json";
      add_header Cache-Control "max-age=604800";
    }
  ingressClassName: nginx
