versions:
  frontend:

frontend:
  name: geoweb
  registry: registry.gitlab.com/opengeoweb/opengeoweb
  svcPort: 80
  containerPort: 8080
  replicas: 1
  minPodsAvailable: 0
  auth_secretName: geoweb-auth
  auth_secretType: secretsmanager
  client_id_secretName: geoweb-client-id
  client_id_secretType: secretsmanager
  spcName: geoweb-spc
  secretServiceAccount: geoweb-service-account
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "1"
  startupProbe:
    httpGet:
      path: /assets/config.json?startup=true
      port: 8080
    periodSeconds: 5
    timeoutSeconds: 5
    failureThreshold: 12  # Allow a minute for startup
  livenessProbe:
    httpGet:
      path: /assets/config.json
      port: 8080
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 2
  readinessProbe:
    httpGet:
      path: /assets/config.json?readiness=true
      port: 8080
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 1
  env:
    GW_AUTH_LOGOUT_URL: "{app_url}"
    GW_AUTH_TOKEN_URL: https://gitlab.com/oauth/token
    GW_AUTH_LOGIN_URL: https://gitlab.com/oauth/authorize?client_id={client_id}&response_type=code&scope=email+openid+read_repository+read_api&redirect_uri={app_url}/code&state={state}&code_challenge={code_challenge}&code_challenge_method=S256
    GW_FEATURE_FORCE_AUTHENTICATION: false
    GW_FEATURE_MODULE_SPACE_WEATHER: false
    GW_FEATURE_MENU_FEEDBACK: false
    GW_FEATURE_MENU_INFO: true
    GW_FEATURE_MENU_VERSION: false
    GW_FEATURE_MENU_FE_VERSION: true
  useCustomConfigurationFiles: false
  customConfigurationLocation: local
  customConfigurationMountPath: /usr/share/nginx/html/assets/custom
  volumeAccessMode: ReadOnlyMany
  volumeSize: 100Mi
  customConfiguration:
    enabled: false
    files:
      "initialPresets.json":
        preset:
          presetType: "mapPreset"
          presetId: "mapPreset-1"
          presetName: "Layer manager preset"
          defaultMapSettings:
            proj:
              bbox:
                left: 58703.6377
                bottom: 6408480.4514
                right: 3967387.5161
                top: 11520588.9031
              srs: "EPSG:3857"
            layers:
              - name: "WorldMap_Light_Grey_Canvas"
                type: "twms"
                enabled: true
                layerType: "baseLayer"
              - service: "https://adaguc-server-geoweb.geoweb.knmi.cloud/adagucserver?dataset=baselayers"
                name: "countryborders"
                format: "image/png"
                enabled: true
                layerType: "overLayer"
          timeSeriesServices:
            - name: "FMI"
              url: "https://opendata.fmi.fi/edr"
              id: "fmi"
              description: "FMI EDR"
              type: "EDR"
              scope: "system"
            - name: "KNMI OBS"
              url: "https://gw-edr.pub.knmi.cloud/edr"
              id: "knmi"
              description: "KNMI EDR"
              type: "EDR"
              scope: "system"
            - name: "KNMI Geoservices"
              url: "https://geoservices.knmi.nl/edr"
              id: "knmi_geoservices_edr"
              description: "KNMI EDR on geoservices with UWCW HA43 DINI"
              type: "EDR"
              scope: "system"
            - name: "MET Norway"
              url: "https://interpol.met.no"
              id: "METNorway"
              description: "MET Norway EDR"
              type: "EDR"
              scope: "system"
          soundingsCollections:
            - name: "Harmonie scandinavia hybrid"
              id: "harmonie_scandinavia_hybrid"
              url: "https://opendata.fmi.fi/edr"
              description: "MEPS/vertical coordinate model level"
            - name: "Harmonie scandinavia pressure"
              id: "harmonie_scandinavia_pressure"
              url: "https://opendata.fmi.fi/edr"
              description: "MEPS/vertical coordinate pressure"
            - name: "ECMWF painepinta"
              id: "ecmwf_painepinta"
              url: "https://opendata.fmi.fi/edr"
              description: "ECMWF/vertical coordinate pressure"
          services:
            - name: "KNMI Radar"
              url: "https://geoservices.knmi.nl/adagucserver?dataset=RADAR"
              id: "knmi-radar"
            - name: "FMI"
              url: "https://openwms.fmi.fi/geoserver/wms?"
              id: "fmi"
            - name: "MET Norway"
              url: "https://halo-wms.met.no/halo/default.map?"
              id: "met-no"
            - name: "Harmonie HA43 DINI"
              url: "https://geoservices.knmi.nl/adagucserver?dataset=uwcw_ha43_dini_5p5km&"
              id: "knmi_uwcw_ha43_dini_5p5km"
            - name: "Harmonie HA43 NL"
              url: "https://geoservices.knmi.nl/adagucserver?dataset=uwcw_ha43_nl_2km&"
              id: "knmi_uwcw_ha43_nl_2km"
            - name: "KNMI Observations"
              url: "https://geoservices.knmi.nl/adagucserver?dataset=OBS"
              id: "knmi-obs"
            - name: "DWD"
              url: "https://maps.dwd.de/geoserver/ows?"
              id: "dwd"
            - name: "EUMETSAT"
              url: "https://view.eumetsat.int/geoserver/wms?"
              id: "eumetsat"
            - name: "ECMWF"
              url: "https://eccharts.ecmwf.int/wms/?token=public"
              id: "ecmwf"
            - name: "NOAA Tropical Cyclones"
              url: "https://mapservices.weather.noaa.gov/tropical/services/tropical/NHC_tropical_weather/MapServer/WMSServer?"
              id: "noaatropicalcyclones"
          baseServices:
            - name: "KNMIBaselayers"
              url: "https://adaguc-server-geoweb.geoweb.knmi.cloud/adagucserver?DATASET=baselayers"
              id: "KNMIgeoservicesBaselayers"
            - name: "geoservicesBaselayers"
              url: "https://geoservices.knmi.nl/wms?DATASET=baselayers"
              id: "geoservicesbaselayers"
            - name: "DWD"
              url: "https://maps.dwd.de/geoserver/ows?"
              id: "base-dwd"
          layers:
            - id: "base-layer-1"
              name: "WorldMap_Light_Grey_Canvas"
              type: "twms"
              layerType: "baseLayer"
            - id: "base-layer-2"
              name: "OpenStreetMap_NL"
              type: "twms"
              layerType: "baseLayer"
              enabled: true
            - id: "base-layer-3"
              service: "https://services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/"
              name: "arcGisCanvas"
              type: "twms"
              layerType: "baseLayer"
              enabled: true
            - service: "https://geoservices.knmi.nl/wms?DATASET=baselayers"
              name: "countryborders"
              id: "countryborders"
              format: "image/png"
              enabled: true
              layerType: "overLayer"

ingress:
  name: nginx-ingress-controller
  rules: |
    add_header Document-Policy "js-profiling" always;
    if ($request_uri ~* \.(json)) {
      add_header Cache-Control "no-cache";
    }
    if ($request_uri ~* \.(woff2|svg)) {
      add_header Cache-Control "max-age=604800";
    }
    if ($request_uri ~* \.(webmanifest)) {
      more_clear_headers 'Content-Type';
      add_header Content-Type "application/manifest+json";
      add_header Cache-Control "max-age=604800";
    }
  ingressClassName: nginx