# Default values for mlflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment:

mlflow:
  replicas: 1
  containerPort: 5000
  servicePort: 5000

  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1"

  image:
    repository: ghcr.io/mlflow/mlflow
    tag: "v3.4.0"
    pullPolicy: Always
    build:
      resources:
        limits:
          memory: 4Gi
        requests:
          memory: 2Gi

objectStorage:
  s3:
    bucketName:
    endpointUrl:
    artifactPath:
    backupPath:

postgresql:
  clusterName: pg-cluster
  database: app
  owner: app
  instances: 3
  storageSize: 3Gi
  parameters:
    # 1/4 of memory as suggested in https://www.postgresql.org/docs/current/runtime-config-resource.html
    sharedBuffers: "128MB"
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  secretName: postgresql-mlflow-secret
