# Default values for mlflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: # test/prod

mlflow:
  replicas: 1
  containerPort: 5000
  servicePort: 5000

  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1"

  image:
    repository: ghcr.io/mlflow/mlflow
    tag: "v3.4.0"
    pullPolicy: Always
    build:
      resources:
        limits:
          memory: "4Gi"
        requests:
          memory: "2Gi"

# Backups
recovery:
  enabled: false

  # ondemand backups use (recovering from a Backup object):
  # https://cloudnative-pg.io/documentation/1.27/recovery/#recovery-from-a-backup-object
  ondemand: false
  name: # name of the manually created backup resource

  # scheduled backups use:
  # https://cloudnative-pg.io/documentation/1.27/appendixes/backup_barmanobjectstore/#recovery-from-an-object-store
  source: external-source # dont change this
  serverName: pg-cluster-source # name of the source cluster (where the backups are taken from)

# S3 storage for artifacts and backups
objectStorage:
  s3:
    secretName: s3-credentials
    bucketName:
    endpointUrl:
    artifactPath:
    backupPath:

# Cloudnative-pg configurations
postgresql:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6
  clusterName: pg-cluster
  database: app
  owner: app
  instances: 3
  storageSize: 3Gi
  parameters:
    # 1/4 of memory as suggested in https://www.postgresql.org/docs/current/runtime-config-resource.html
    sharedBuffers: "128MB"
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  secrets:
    admin: postgresql-superuser-secret
    mlflow: postgresql-mlflow-secret
