#Default values
image:
  repository: quay.io/fmi/smartmet-server
  pullPolicy: IfNotPresent
  tag: 0.1.6
  pullSecret: fmi-openshift-pull-secret

# This applies both image and filesys2smartmet
pvc:
  name: ""
  mountPath: ""
  claimName: ""

secrets:
  name: smartmet-server-sealedsecrets

serviceAccount:
  enabled: true
  name: ptrace-sa-v1

resources:
  requests:
    memory: 8Gi
    cpu: 1
  limits:
    memory: 16Gi
    cpu: 2

config:
  locale: "fi_FI.UTF-8"
  logrequests: true
  defaultlogging: false
  accesslogdir: "/var/log/smartmet"
  port: 8080
  verbose: false
  lazylinking: true
  activerequests:
    start_limit: 10
    restart_limit: 5
    limit: 100
    increase_interval: 5
    alert_limit: 50
  maxrequestsize: 131072
  compress: true
  compresslimit: 1000
  stacktrace: false
  slowpool:
    maxthreads: 10
    maxrequeuesize: 100
  fastpool:
    maxthreads: "20"
    maxrequeuesize: 200
  adminpool:
    maxthreads: 5
    maxrequeuesize: 50
  redis:
    # enable local redis
    # if disabled must specify remote redis address and port
    enabled: true
    address: ""
    port: 6379
    tablePrefix: "smartmet."
  engines:
    authentication:
      disabled: true
    avi:
      disabled: true
    contour:
      disabled: true
    geonames:
      disabled: true
    gis:
      disabled: true
      quiet: true
    grid:
      disabled: true
      memoryMapper:
        enabled: true
      logging:
        processing:
          enabled: false
        debug:
          enabled: false
    observation:
      disabled: true
    querydata:
      disabled: true
    sputnik:
      disabled: false
  plugins:
    admin:
      disabled: true
    autocomplete:
      disabled: true
    avi:
      disabled: true
    backend:
      disabled: false
    cross_section:
      disabled: true
    download:
      disabled: true
    meta:
      disabled: true
    textgen:
      disabled: true
    timeseries:
      disabled: true
    trajectory:
      disabled: true
    wms:
      disabled: true
    wfs:
      disabled: true
    grid_gui:
      disabled: true
    grid_admin:
      disabled: true
    edr:
      disabled: true

# name: Producer name (must correspond to the producer name in the producers section)
# mapping_name: Mapping name
# parameter_id_type: Parameter id type:
#         1 = FMI_ID
#         2 = FMI_NAME
#         3 = GRIB_ID
#         4 = NEWBASE_ID
#         5 = NEWBASE_NAME
#         6 = NETCDF_NAME
# parameter_id: Parameter id
# geometry_id: Geometry id
# level_id_type: Level id type:
#         1 = FMI
#         2 = GRIB1
#         3 = GRIB2
# level_id: Level id
#         FMI level identifiers:
#            1 Gound or water surface
#            2 Pressure level
#            3 Hybrid level
#            4 Altitude
#            5 Top of atmosphere
#            6 Height above ground in meters
#            7 Mean sea level
#            8 Entire atmosphere
#            9 Depth below land surface
#            10 Depth below some surface
#            11 Level at specified pressure difference from ground to level
#            12 Max equivalent potential temperature level
#            13 Layer between two metric heights above ground
#            14 Layer between two depths below land surface
#            15 Isothermal level, temperature in 1/100 K
# level: Level
# area_interpolation_method: Area interpolation method
#         0 = None
#         1 = Linear
#         2 = Nearest
#         3 = Min
#         4 = Max
#         9 = Landscape
#         10 = Forbidden
#         500..999 = List
#         1000..65535 = External (interpolated by an external function)
# time_interpolation_method: Time interpolation method
#         0 = None
#         1 = Linear
#         2 = Nearest
#         3 = Min
#         4 = Max
#         6 = Previous
#         7 = Next
#         1000..65535 = External (interpolated by an external function)
# level_interpolation_method: Level interpolation method
#         0 = None
#         1 = Linear
#         2 = Nearest
#         3 = Min
#         4 = Max
#         5 = Logarithmic
#         6 = Previous
#         7 = Next
#         1000..65535 = External (interpolated by an external function)
# group_flags: Group flags
#         bit 0 = Climatological parameter (=> ignore year when searching)
#         bit 1 = Global parameter (=> ignore timestamp when searching, for example LandSeaMask)
# search_match: Search match (Can this mapping used when searching mappings for incomplete parameters)
#         E = Enabled
#         D = Disabled
#         I = Ignore
# mapping_function: Mapping function (enables data conversions during the mapping)
# reverse_mapping_function: Reverse mapping function
# default_precision: Default precision
mappings:
  # - name: "demo"
  #   mapping_name: "TD-K"
  #   parameter_id_type: 2
  #   parameter_id: "TD-K"
  #   geometry_id: 1110
  #   level_id_type: 1
  #   level_id: 6
  #   level: "00002"
  #   area_interpolation_method: 1
  #   time_interpolation_method: 1
  #   level_interpolation_method: 1
  #   group_flags: 0
  #   search_match: "E"
  #   mapping_function: ""
  #   reverse_mapping_function: ""
  #   default_precision: ""

producers:
  # - name: "demo"
  #   abbreviation: "demo"
  #   title: "demo-title"
  #   description: "demo-desription"
  #   geometryId: 1110

logging:
  target: "stdout"
  directory: ""

filesys2smartmet:
  enabled: false
  image:
    repository: quay.io/fmi/smartmet-server
    pullPolicy: IfNotPresent
    tag: filesys2smartmet-0.1.0
  config:
    loopInterval: 60
    memoryMapper:
      enabled: false
  data:

# requires RADON_USER and RADON_PASSWORD in sealed secret
radon2smartmet:
  enabled: false
  image:
    repository: quay.io/fmi/smartmet-server
    pullPolicy: IfNotPresent
    tag: radon2smartmet-0.0.1
  config:
    loopInterval: 30
    radon:
      host: ""
      database: ""
    gridfiles:
      #TODO clean this
      configFile: "/config/libraries/grid-files/grid-files.conf"
