# Default values for smartmetserver chart.

# Chart name overrides
nameOverride: ""
fullnameOverride: ""

image:
  repository: fmidev/smartmetserver
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

smartmetserver:
  name: smartmetserver
  containerPort: 8080
  svcPort: 80
  replicas: 2
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 5
  startupProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 5
  # Resource limits and requests for the container
  resources:
    limits:
      memory: 4Gi
      cpu: "2"
    requests:
      cpu: "0.5"
      memory: 2Gi

# Service configuration
service:
  type: ClusterIP
  portName: http
  targetPort: 8080
  annotations: {}
  # sessionAffinity: ClientIP

ingress:
  enabled: false
  name: nginx-ingress
  ingressClassName: ""
  # List of hosts for the ingress
  hosts: []
  # Example:
  # hosts:
  #   - smartmetserver.example.com
  # Custom annotations for the ingress
  annotations: {}
  # Example:
  # annotations:
  #   nginx.ingress.kubernetes.io/ssl-redirect: "true"
  #   nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  # Custom paths configuration
  paths:
    - path: /
      pathType: Prefix
  tls:
    enabled: false
    secretName: smartmetserver-ingress-tls
    issuerRef:
      kind: ClusterIssuer
      name: letsencrypt

# Volume configuration for smartmet data
volume:
  # Volume type: "cephfs", "nfs", or "hostPath"
  type: hostPath
  # Whether the volume should be mounted as read-only
  readOnly: true
  # Provisioning mode: "static" (use existing PV) or "dynamic" (create new PV)
  provisioning: dynamic

  # hostPath configuration (for local directory on node)
  hostPath:
    path: /tmp/smartmet-data
    # PV/PVC configuration for hostPath
    pv:
      name: smartmet-data-pv
      storageClassName: ""
    pvc:
      name: smartmet-data-pvc
      accessModes: ReadWriteOnce
      storage: 1Gi
      # For dynamic provisioning, specify storageClassName (empty = use default)
      storageClassName: ""

  # NFS configuration
  nfs:
    server: 10.12.12.66
    path: /smartmet/data

  # CephFS configuration
  cephfs:
    # PV/PVC configuration for CephFS
    pv:
      name: smartmet-data-pv
      capacity: 10Ti  # Metadata only for existing volumes - adjust to match your actual volume size
      fsName: smartmet_data
      rootPath: /
      clusterID: smartmet-ceph
      secretName: cephfs-secret
      secretNamespace: ceph-csi
    pvc:
      name: smartmet-data-pvc
      capacity: 10Ti  # Must match PV capacity - adjust to match your actual volume size
      # For dynamic provisioning, specify storageClassName
      storageClassName: csi-cephfs

hpa:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60
  # Optional memory utilization target (uncomment to enable)
  # targetMemoryUtilizationPercentage: 70
  # Optional behavior configuration for fine-tuned scaling
  # behavior:
  #   scaleDown:
  #     stabilizationWindowSeconds: 300
  #     policies:
  #       - type: Percent
  #         value: 50
  #         periodSeconds: 60
  #   scaleUp:
  #     stabilizationWindowSeconds: 60
  #     policies:
  #       - type: Percent
  #         value: 100
  #         periodSeconds: 15

# Pod Disruption Budget configuration for high availability
podDisruptionBudget:
  enabled: true
  # Minimum number of pods that must remain available during voluntary disruptions
  # Use either minAvailable OR maxUnavailable, not both
  minAvailable: 1
  # Alternative: specify maximum unavailable pods
  # maxUnavailable: 1
  # maxUnavailable: "50%"  # Can also use percentages

smartmetConf:
  # Basic server configuration
  server:
    port: 8080
    defaultlogging: false
    logrequests: true
    verbose: true
    debug: true
    lazylinking: true
    compress: true
    compresslimit: 1000

  # Thread pool configuration
  pools:
    slowpool:
      maxthreads: 24
      maxrequeuesize: 100
    fastpool:
      maxthreads: 24
      maxrequeuesize: 100

  # List of engines to enable
  engines:
    - sputnik
    - contour
    - geonames
    - gis
    - querydata
    - grid

  # List of plugins to enable
  plugins:
    - autocomplete
    - download
    - edr
    - timeseries
    - wms

  # QueryData engine configuration (optional)
  # If not provided, a default template will be generated
  querydata: |
    @include "querydata/translations.conf"
    verbose = true;
    valid_points_cache_dir = "/var/smartmet/cache/validpoints";
    producers = ["demo_surface"];
    demo_surface:
    {
        directory = "/smartmet/data/demo/surface/querydata";
        pattern = ".*demo.*\.sqd$";
        forecast = true;
        type = "grid";
        leveltype = "surface";
        refresh_interval_secs = 60;
        number_to_keep = 1;
        multifile = false;
    };
