# use camelCase for keys
# add all default parameters to everything
# validate all required parameters
# add schema when everything is finished

image:
  repository: fmidev/smartmetserver
  pullPolicy: IfNotPresent
  tag: latest

#Diff: change name to avoid confusion with multiple charts
#do we need all these settings?
server:
  name: smartmetserver
  containerPort: 8080
  #diff: use full names
  servicePort: 8080
  replicas: 2
  livenessProbe:
    periodSeconds: 30
  readinessProbe:
    failureThreshold: 5
    periodSeconds: 60
  startupProbe:
    failureThreshold: 5
    periodSeconds: 60

  #diff use yaml
  config:
    port: 8080
    defaultlogging: false
    logrequests: true
    accesslogdir: "/var/log/smartmet"
    verbose: true
    debug: true
    lazylinking: true
    compress: true
    compresslimit: 1000
    slowpool:
      maxthreads: 24
      maxrequeuesize: 100
    fastpool:
      maxthreads: 24
      maxrequeuesize: 100
    
    engines:
      sputnik:
        enabled: true
        # these should be default in template
        configfile: "engines/sputnik.conf"
      contour:
        enabled: true
        configfile: "engines/contour.conf"
      geonames:
        enabled: true
        configfile: "engines/geonames.conf"
      gis:
        enabled: true
        configfile: "engines/gis.conf"
      querydata:
        enabled: true
        configfile: "engines/querydata.conf"
      grid:
        enabled: true
        configfile: "engines/grid.conf"
    plugins:
      admin:
        enabled: true
        configfile: "plugins/admin.conf"
      autocomplete:
        enabled: true
        configfile: "plugins/autocomplete.conf"
      download:
        enabled: true
        configfile: "plugins/download.conf"
      edr:
        enabled: true
        configfile: "plugins/edr.conf"
      timeseries:
        enabled: true
        configfile: "plugins/timeseries.conf"
      wms:
        enabled: true
        configfile: "plugins/wms.conf"

fminames:
# need to validate required parameters
  connection:
    host: "localhost"
    port: 1234

gis:
  # need to validate required parameters
  connection:
    host: "localhost"
    port: 1234

#change templated names to not require names in ingress, persistentVolume, persistentVolumeClaim, horizontalPodAutoscaler etc.
ingress:
  enable: true
  ingressClassName: ""

#diff use full name
persistentVolume:
  enable: true
  path: /tmp/smartmet-data

#diff use full name
persistentVolumeClaim:
  enable: true
  storageClassName: hostpath-smartmet
  # cant use readwriteonce if multiple replicas?
  accessModes: ReadWriteOnce
  storage: 1Gi

#diff use full name
horizontalPodAutoscaler:
  enable: true
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60

