image:
  repository: fmidev/smartmetserver
  pullPolicy: IfNotPresent
  tag: latest

smartmetserver:
  name: smartmetserver
  containerPort: 8080
  svcPort: 8080
  replicas: 2

ingress:
  name: nginx-ingress
  ingressClassName: ""

pvc:
  name: pvc
  storageClassName: local
  accessModes: ReadWriteOnce
  storage: 1Gi
