image:
  repository: fmidev/smartmetserver
  pullPolicy: IfNotPresent
  tag: latest

smartmetserver:
  name: smartmetserver
  containerPort: 8080
  svcPort: 8080
  replicas: 2


ingress:
  name: nginx-ingress


namespace:
  name: smartmet

pvc:
  name: pvc
  storageClassName: local
  accessModes: ReadWriteOnce
  storage: 1Gi
