# Default values for smartmetserver chart.

# Chart name overrides
nameOverride: ""
fullnameOverride: ""

image:
  repository: fmidev/smartmetserver
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

smartmetserver:
  name: smartmetserver
  containerPort: 8080
  svcPort: 80
  replicas: 2
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 5
  startupProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 5
  # Resource limits and requests for the container
  resources:
    limits:
      memory: 4Gi
      cpu: "2"
    requests:
      cpu: "0.5"
      memory: 2Gi

# Security configuration
securityContext:
  # Pod-level security context
  pod:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
    seLinuxOptions:
      level: "s0"

  # Container-level security context (for container-specific settings)
  container:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

# Service Account configuration
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the
  # fullname template
  name: ""
  # Automatically mount a ServiceAccount's API credentials
  automountServiceAccountToken: false

# Service configuration
service:
  type: ClusterIP
  portName: http
  targetPort: 8080
  annotations: {}
  # sessionAffinity: ClientIP

ingress:
  enabled: false
  name: nginx-ingress
  ingressClassName: ""
  # List of hosts for the ingress
  hosts: []
  # Example:
  # hosts:
  #   - smartmetserver.example.com
  # Custom annotations for the ingress
  annotations: {}
  # Example:
  # annotations:
  #   nginx.ingress.kubernetes.io/ssl-redirect: "true"
  #   nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  # Custom paths configuration
  paths:
    - path: /
      pathType: Prefix
  tls:
    enabled: false
    secretName: smartmetserver-ingress-tls
    issuerRef:
      kind: ClusterIssuer
      name: letsencrypt

# Volume configuration for smartmet data
volume:
  # Volume type: "cephfs", "nfs", or "hostPath"
  type: hostPath
  # Whether the volume should be mounted as read-only
  readOnly: true
  # Provisioning mode: "static" (use existing PV) or "dynamic" (create new PV)
  provisioning: dynamic

  # hostPath configuration (for local directory on node)
  hostPath:
    path: /tmp/smartmet-data
    # PV/PVC configuration for hostPath
    pv:
      name: smartmet-data-pv
      storageClassName: ""
    pvc:
      name: smartmet-data-pvc
      accessModes: ReadWriteOnce
      storage: 1Gi
      # For dynamic provisioning, specify storageClassName (empty = use default)
      storageClassName: ""

  # NFS configuration
  nfs:
    server: 10.12.12.66
    path: /smartmet/data

  # CephFS configuration
  cephfs:
    # PV/PVC configuration for CephFS
    pv:
      name: smartmet-data-pv
      # Metadata only for existing volumes - adjust to match your actual
      # volume size
      capacity: 10Ti
      fsName: smartmet_data
      rootPath: /
      clusterID: smartmet-ceph
      secretName: cephfs-secret
      secretNamespace: ceph-csi
    pvc:
      name: smartmet-data-pvc
      # Must match PV capacity - adjust to match your actual volume size
      capacity: 10Ti
      # For dynamic provisioning, specify storageClassName
      storageClassName: csi-cephfs

hpa:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60
  # Optional memory utilization target (uncomment to enable)
  # targetMemoryUtilizationPercentage: 70
  # Optional behavior configuration for fine-tuned scaling
  # behavior:
  #   scaleDown:
  #     stabilizationWindowSeconds: 300
  #     policies:
  #       - type: Percent
  #         value: 50
  #         periodSeconds: 60
  #   scaleUp:
  #     stabilizationWindowSeconds: 60
  #     policies:
  #       - type: Percent
  #         value: 100
  #         periodSeconds: 15

# Pod Disruption Budget configuration for high availability
podDisruptionBudget:
  enabled: true
  # Minimum number of pods that must remain available during voluntary
  # disruptions. Use either minAvailable OR maxUnavailable, not both
  minAvailable: 1
  # Alternative: specify maximum unavailable pods
  # maxUnavailable: 1
  # maxUnavailable: "50%"  # Can also use percentages

smartmetConf:
  # Basic server configuration
  server:
    port: 8080
    defaultlogging: false
    logrequests: true
    verbose: true
    debug: true
    lazylinking: true
    compress: true
    compresslimit: 1000

  # Thread pool configuration
  pools:
    slowpool:
      maxthreads: 24
      maxrequeuesize: 100
    fastpool:
      maxthreads: 24
      maxrequeuesize: 100

  # List of engines to enable
  engines:
    - sputnik
    - contour
    - geonames
    - gis
    - querydata
    - grid

  # List of plugins to enable
  plugins:
    - autocomplete
    - download
    - edr
    - timeseries
    - wms

  # QueryData engine configuration
  # 
  # You can configure querydata in three ways:
  # 
  # 1. Structured configuration (recommended) - Define producers with levels:
  #
  # querydata:
  #   # Global settings
  #   basePath: "/smartmet/data"        # Default base directory
  #   defaultArea: "world"               # Default geographical area
  #   
  #   # Global defaults for all producers
  #   defaults:
  #     forecast: true
  #     type: "grid"
  #     refresh_interval_secs: 60
  #     number_to_keep: 4
  #     multifile: false
  #     alias: ""                        # Empty string = no alias line
  #   
  #   # Producer definitions
  #   producers:
  #     - name: ecmwf
  #       area: "kenya"                  # Override default area
  #       forecast: true                 # Optional producer-level override
  #       levels:
  #         surface:
  #           alias: ["ecmwf"]           # Can be string or array
  #           number_to_keep: 4          # Level-specific override
  #         pressure:
  #           alias: "ecmwf_pressure"
  #           number_to_keep: 2
  #           multifile: null            # null = omit multifile line
  #     
  #     - name: gfs
  #       levels:
  #         surface:
  #           alias: ["gfs"]
  #         pressure: {}                 # Uses all defaults
  #
  # 2. Raw configuration - Provide complete config as a string:
  #
  # querydata:
  #   raw: |
  #     @include "querydata/translations.conf"
  #     verbose = true;
  #     producers = ["custom"];
  #     custom:
  #     {
  #         directory = "/custom/path";
  #         pattern = ".*\.sqd$";
  #     };
  #
  # 3. Legacy string format (backward compatible):
  #
  querydata: |
    @include "querydata/translations.conf"
    verbose = true;
    valid_points_cache_dir = "/var/smartmet/cache/validpoints";
    producers = ["demo_surface"];
    demo_surface:
    {
        directory = "/smartmet/data/demo/surface/querydata";
        pattern = ".*demo.*\.sqd$";
        forecast = true;
        type = "grid";
        leveltype = "surface";
        refresh_interval_secs = 60;
        number_to_keep = 1;
        multifile = false;
    };
