image:
  repository: fmidev/smartmetserver
  pullPolicy: IfNotPresent
  tag: latest

smartmetserver:
  name: smartmetserver
  containerPort: 8080
  svcPort: 8080
  replicas: 2

ingress:
  name: nginx-ingress
  ingressClassName: ""

pv:
  enable: true
  name: pv
  path: /tmp/smartmet-data

pvc:
  name: pvc
  storageClassName: hostpath-smartmet
  accessModes: ReadWriteOnce
  storage: 1Gi
