apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geoweb-plugin-registry.fullname" . }}-config
  labels:
    {{- include "geoweb-plugin-registry.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Files.Get "files/config.local.yaml" | indent 4 }}

