{{- if .Values.auth.secretProviderClass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ default (printf "%s-oidc" (include "geoweb-plugin-registry.fullname" .)) .Values.auth.secretProviderClass.name | quote }}
  labels:
    {{- include "geoweb-plugin-registry.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    region: {{ .Values.auth.secretProviderClass.region | quote }}
    objects: |
      - objectName: {{ .Values.auth.secretProviderClass.objectName | quote }}
        objectType: "secretsmanager"
        jmesPath:
          - path: {{ .Values.auth.clientIdKey | quote }}
            objectAlias: "oidc-client-id"
          - path: {{ .Values.auth.clientSecretKey | quote }}
            objectAlias: "oidc-client-secret"
  secretObjects:
    - secretName: {{ .Values.auth.secretName | quote }}
      type: Opaque
      data:
        - objectName: "oidc-client-id"
          key: {{ .Values.auth.clientIdKey | quote }}
        - objectName: "oidc-client-secret"
          key: {{ .Values.auth.clientSecretKey | quote }}
{{- end }}
