apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: {{ .Release.Name }}-port
      port: {{ .Values.config.port }}
      targetPort: {{ .Values.config.port }}