versions:
  location:

location:
  name: location
  registry: registry.gitlab.com/opengeoweb/backend-services/location-backend/location-backend
  path: /location-backend/(.*)
  svcPort: 80
  containerPort: 8080
  replicas: 1
  minPodsAvailable: 0
  resources:
    requests:
      memory: "384Mi"
      cpu: "50m"
    limits:
      memory: "1024Mi"
      cpu: "1"
  startupProbe:
    httpGet:
      path: /healthcheck?startup=true
      port: 8080
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 24  # Allow 4 minutes for startup
  livenessProbe:
    httpGet:
      path: /
      port: 8080
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 2
  readinessProbe:
    httpGet:
      path: /healthcheck?readiness=true
      port: 8080
    periodSeconds: 20
    timeoutSeconds: 10
    failureThreshold: 1
  env:
    APPLICATION_DOC_ROOT: "/api"
    APPLICATION_ROOT_PATH: "/location-backend"
    LOCALDATA: "True"
    MAX_RESULTS: 100
    DEFAULT_TIMEOUT: 15
    LOG_LEVEL: "INFO"

ingress:
  name: nginx-ingress-controller
  ingressClassName: nginx
