{{ if .Values.radon2smartmet.enabled}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radon2smartmet
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ default "smartmet-server-serviceaccount" .Values.serviceAccount.name }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsGroup: 0
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      initContainers:
      {{- if .Values.config.redis.enabled }}
      - name: wait-for-redis
        image: busybox
        command: ['/bin/sh', '-c']
        args:
        - |
          until echo quit | telnet {{ default (printf "redis-master.%s" .Release.Name) .Values.config.redis.address }} {{ default 6379 .Values.config.redis.port }} ; do
            echo 'waiting for database...'
            sleep 2
          done
      {{- end }}
      containers:
        - name: radon2smartmet
          securityContext:
            runAsGroup: 0
            capabilities:
              add:
              - SYS_PTRACE
          resources:
            requests:
              memory: {{ default "8Gi" .Values.resources.requests.memory }}
              cpu: {{ default "1" .Values.resources.requests.cpu }}
            limits:
              memory: {{ default "16Gi" .Values.resources.limits.memory }}
              cpu: {{ default "2" .Values.resources.limits.cpu }}
          image: {{ .Values.radon2smartmet.image.repository }}:{{ .Values.radon2smartmet.image.tag }}
          {{- if .Values.radon2smartmet.image.pullPolicy }}
          imagePullPolicy: {{ .Values.radon2smartmet.image.pullPolicy }}
          {{- end }}
          command: ["/usr/local/bin/run.sh", "{{ default 30 .Values.radon2smartmet.config.loopInterval}}" ]
          env:
            - name: REDIS_CONTENT_SERVER_ADDRESS
              value: "{{ default "redis-master.{{ .Release.Name }}" .Values.config.redis.address }}"
            - name: REDIS_CONTENT_SERVER_PORT
              value: "{{ default 6379 .Values.config.redis.port }}"
            - name: REDIS_CONTENT_SERVER_TABLE_PREFIX
              value: "{{ default "smartmet." .Values.config.redis.tablePrefix }}"
            - name: RADON_USER
              valueFrom:
                secretKeyRef:
                  name: smartmet-server-sealedsecrets
                  key: RADON_USER
            - name: RADON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smartmet-server-sealedsecrets
                  key: RADON_PASSWORD
            - name: RADON_HOST
              value: "{{ default "" .Values.radon2smartmet.config.radon.host }}"
            - name: RADON_DATABASE
              value: "{{ default "" .Values.radon2smartmet.config.radon.database }}"
            - name: RADON_PRODUCERFILE
              value: "{{ default "/config/libraries/tools-grid/producers.csv" .Values.radon2smartmet.config.radon.producerfile }}"
            - name: GRID_FILES_LIBRARY_CONFIG_FILE
              value: "{{ default "/config/libraries/grid-files/grid-files.conf" .Values.radon2smartmet.config.gridfiles.configFile }}"
            - name: GRID_TOOLS_CONFIG_DIR
              value: "/config"
            - name: CORBA_CONTENT_SERVER_IOR
              value: ""
            - name: HTTP_CONTENT_SERVER_URL
              value: ""
          volumeMounts:
            - name: radon-to-smartmet-config
              mountPath: "/config/radon-to-smartmet.cfg"
              subPath: "radon-to-smartmet.cfg"
      volumes:
        - name: radon-to-smartmet-config
          configMap:
            name: radon-to-smartmet-config
            items:
              - key: configuration
                path: radon-to-smartmet.cfg
{{- end }}