apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "fmi-rpm-repo-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8888
      protocol: TCP
      name: 8888-tcp
  selector:
    app: {{ .Release.Name }}
