apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mlflow.fullname" . }}-config
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
data:
  BUCKET_NAME: {{ .Values.objectStorage.s3.bucketName }}
  S3_ENDPOINT_URL: {{ .Values.objectStorage.s3.endpointUrl }}
