apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    type: external
spec:
  host: {{ .Release.Namespace }}.out.{{ include "environment" . }}.fmi.fi
  port:
    targetPort: {{ .Values.mlflow.servicePort }}
  to:
    kind: Service
    name: mlflow
    weight: 100
  tls:
    termination: edge
