apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlflow.fullname" . }}
spec:
  selector:
    {{- include "mlflow.selectorLabels" . | nindent 4 }}

  ports:
    - protocol: TCP
      port: {{ .Values.mlflow.servicePort | default 5000 }}
      targetPort: {{ .Values.mlflow.containerPort | default 5000 }}
