apiVersion: v1
metadata:
  name: logging-configmap
data:
  config: |
    {{- $log := .Values.logging | default (dict "level" "INFO") -}}
    {{- $log_level := (default "INFO" $log.level) | upper }} 
    [loggers]
    keys=root,traffic-logger,router-logger,json-logger

    [handlers]
    keys=consoleHandler,jsonHandler

    [formatters]
    keys=consoleFormatter,jsonFormatter

    [logger_root]
    level={{ $log_level }}
    handlers=consoleHandler
    qualname=root
    propagate=0

    [logger_traffic-logger]
    level={{ $log_level }}
    handlers=consoleHandler
    qualname=traffic-logger
    propagate=0

    [logger_router-logger]
    level={{ $log_level }}
    handlers=consoleHandler
    qualname=router-logger
    propagate=0

    [logger_json-logger]
    level={{ $log_level }}
    handlers=jsonHandler
    qualname=json-logger
    propagate=0

    [handler_consoleHandler]
    class=StreamHandler
    level={{ $log_level }}
    formatter=consoleFormatter
    args=(sys.stdout,)

    [handler_jsonHandler]
    class=StreamHandler
    level={{ $log_level }}
    formatter=jsonFormatter
    args=(sys.stdout,)

    [formatter_consoleFormatter]
    format=%(asctime)s - %(name)s - %(levelname)s - %(message)s

    [formatter_jsonFormatter]
    format=%(message)s %(levelname)s %(name)s %(asctime)s
    class=pythonjsonlogger.jsonlogger.JsonFormatter
kind: ConfigMap
