apiVersion: v1
metadata:
  name: tnsnames-configmap
data:
  config: |
    CLDB =
      (DESCRIPTION =
        (ADDRESS = (PROTOCOL = TCP)(HOST = oracle.fmi.fi)(PORT = 1521))
        (ADDRESS = (PROTOCOL = TCP)(HOST = oracle-b.fmi.fi)(PORT = 1521))
        (CONNECT_DATA =
          (SERVER = DEDICATED)
          (SERVICE_NAME = cldb)
          (FAILOVER_MODE =
            (TYPE=select)
            (METHOD=basic)
              (RETRIES=20)
              (DELAY=3)
            )
          )
        )
    PRJTK =
      (DESCRIPTION =
        (ADDRESS = (PROTOCOL = TCP)(HOST = oracle.fmi.fi)(PORT = 1521))
        (CONNECT_DATA =
          (SERVER = DEDICATED)
          (SERVICE_NAME = prjtk)
          (FAILOVER_MODE =
            (TYPE=select)
            (METHOD=basic)
              (RETRIES=20)
              (DELAY=3)
            )
          )
        )
kind: ConfigMap
