secrets:
  provider: aws
  namespace: kube-system
  spcName: aws-secrets
  csiName: csi-secrets-store
  serviceAccountName: geoweb-eks-secret-service-account

providerAwsInstaller:
  name: provider-aws-installer
  registry: public.ecr.aws/aws-secrets-manager/secrets-store-csi-driver-provider-aws