versions:
  cap:

cap:
  name: cap
  registry: registry.gitlab.com/opengeoweb/backend-services/cap-backend/cap-backend
  path: /cap/(.*)
  svcPort: 80
  containerPort: 8080
  replicas: 1
  minPodsAvailable: 0
  resources:
    requests:
      memory: "512Mi"
      cpu: "50m"
    limits:
      memory: "1024Mi"
      cpu: "100m"
  startupProbe:
    httpGet:
      path: /healthcheck?startup=true
      port: 8080
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 24  # Allow 4 minutes for startup
  livenessProbe:
    httpGet:
      path: /
      port: 8080
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 2
  readinessProbe:
    httpGet:
      path: /healthcheck?readiness=true
      port: 8080
    periodSeconds: 20
    timeoutSeconds: 10
    failureThreshold: 1
  env:
    APPLICATION_ROOT_PATH: "/cap"

ingress:
  name: nginx-ingress-controller
  ingressClassName: nginx
