versions:
  cap: "v0.3.0"

cap:
  name: cap
  registry: registry.gitlab.com/opengeoweb/backend-services/cap-backend
  path: /cap/(.*)
  svcPort: 80
  containerPort: 8080
  replicas: 1

ingress:
  name: nginx-ingress-controller # Sync with nginx-ingress-controller/values.yaml