versions:
  cap:

cap:
  name: cap
  registry: registry.gitlab.com/opengeoweb/backend-services/cap-backend
  path: /cap/(.*)
  svcPort: 80
  containerPort: 8080
  replicas: 1
  minPodsAvailable: 0
  resources:
    requests:
      memory: "384Mi"
      cpu: "50m"
    limits:
      memory: "1024Mi"
      cpu: "1"
  livenessProbe:
    httpGet:
      path: /healthcheck
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5
    failureThreshold: 5
  readinessProbe:
    httpGet:
      path: /healthcheck?readiness=true
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5
    failureThreshold: 1
  env:
    APPLICATION_ROOT_PATH: "/cap"

ingress:
  name: nginx-ingress-controller
  ingressClassName: nginx
