apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.taf.name }}
spec:
  selector:
    app: {{ .Values.taf.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.taf.svcPort }}
      targetPort: {{ .Values.taf.nginx.NGINX_PORT_HTTP }}