apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.taf.placeholder.name }}
  annotations:
  {{- if .Values.taf.commitHash }}
    commitHash: {{ .Values.taf.commitHash }}
  {{- end }}
data:
  TAFPLACEHOLDER_KEEPRUNNING: {{ .Values.taf.placeholder.TAFPLACEHOLDER_KEEPRUNNING | quote }}