apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.taf.name }}
  labels:
    app: {{ .Values.taf.name }}
spec:
  replicas: {{ .Values.taf.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.taf.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.taf.name }}
      annotations:
        eks.amazonaws.com/compute-type: ec2
      {{- if .Values.taf.commitHash }}
        commitHash: {{ .Values.taf.commitHash }}
      {{- end }}
    spec:
    {{- if eq .Values.secretProvider "aws" }}
      serviceAccountName: {{ .Values.taf.secretServiceAccount }}
    {{- end }}
      containers:
      - name: {{ .Values.taf.name }}
        image: {{ .Values.taf.registry }}:{{ .Values.versions.taf }}
      {{- if .Values.taf.imagePullPolicy }}
        imagePullPolicy: {{ .Values.taf.imagePullPolicy }}
      {{- end }}
      {{- if .Values.taf.postStartCommand }}
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", {{ .Values.taf.postStartCommand | quote }}]
      {{- end }}
        ports:
        - containerPort: {{ .Values.taf.env.AVIATION_TAF_PORT_HTTP }}
      {{- if .Values.taf.resources }}
        resources: {{ toYaml .Values.taf.resources | nindent 10 }}
      {{- end }}
      {{- if .Values.taf.livenessProbe }}
        livenessProbe: {{ toYaml .Values.taf.livenessProbe | nindent 10 }}
      {{- end }}
      {{- if .Values.taf.readinessProbe }}
        readinessProbe: {{ toYaml .Values.taf.readinessProbe | nindent 10 }}
      {{- end }}
        envFrom:
        - configMapRef:
            name: {{ .Values.taf.name }}
        env:
        - name: AVIATION_TAF_BACKEND_DB
          valueFrom:
            secretKeyRef:
              name: {{ .Values.taf.db_secretName }}
              key: AVIATION_TAF_BACKEND_DB
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      - name: {{ .Values.taf.placeholder.name }}
        image: {{ .Values.taf.placeholder.registry }}:{{ .Values.versions.taf }}
      {{- if .Values.taf.imagePullPolicy }}
        imagePullPolicy: {{ .Values.taf.imagePullPolicy }}
      {{- end }}
        ports:
        - containerPort: {{ .Values.taf.placeholder.port }}
      {{- if .Values.taf.placeholder.resources }}
        resources: {{ toYaml .Values.taf.placeholder.resources | nindent 10 }}
      {{- end }}
      {{- if .Values.taf.placeholder.livenessProbe }}
        livenessProbe: {{ toYaml .Values.taf.placeholder.livenessProbe | nindent 10 }}
      {{- end }}
      {{- if .Values.taf.placeholder.readinessProbe }}
        readinessProbe: {{ toYaml .Values.taf.placeholder.readinessProbe | nindent 10 }}
      {{- end }}
        envFrom:
        - configMapRef:
            name: {{ .Values.taf.placeholder.name }}
        env:
        - name: AVIATION_TAF_BACKEND_DB
          valueFrom:
            secretKeyRef:
              name: {{ .Values.taf.db_secretName }}
              key: AVIATION_TAF_BACKEND_DB
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      - name: {{ .Values.taf.messageconverter.name }}
        image: {{ .Values.taf.messageconverter.registry }}:{{ .Values.taf.messageconverter.version }}
      {{- if .Values.taf.imagePullPolicy }}
        imagePullPolicy: {{ .Values.taf.imagePullPolicy }}
      {{- end }}
        env:
        - name: AVI_CONTAINER_PORT
          value: {{ .Values.taf.messageconverter.port | quote }}
        ports:
        - containerPort: {{ .Values.taf.messageconverter.port }}
      {{- if .Values.taf.messageconverter.resources }}
        resources: {{ toYaml .Values.taf.messageconverter.resources | nindent 10 }}
      {{- end }}
      {{- if .Values.taf.messageconverter.livenessProbe }}
        livenessProbe: {{ toYaml .Values.taf.messageconverter.livenessProbe | nindent 10 }}
      {{- end }}
      {{- if .Values.taf.messageconverter.readinessProbe }}
        readinessProbe: {{ toYaml .Values.taf.messageconverter.readinessProbe | nindent 10 }}
      {{- end }}
        envFrom:
        - configMapRef:
            name: {{ .Values.taf.name }}
      - name: {{ .Values.taf.publisher.name }}
        image: {{ .Values.taf.publisher.registry }}:{{ .Values.versions.taf }}
      {{- if .Values.taf.imagePullPolicy }}
        imagePullPolicy: {{ .Values.taf.imagePullPolicy }}
      {{- end }}
        ports:
        - containerPort: {{ .Values.taf.publisher.port }}
      {{- if .Values.taf.publisher.resources }}
        resources: {{ toYaml .Values.taf.publisher.resources | nindent 10 }}
      {{- end }}
      {{- if .Values.taf.publisher.livenessProbe }}
        livenessProbe: {{ toYaml .Values.taf.publisher.livenessProbe | nindent 10 }}
      {{- end }}
      {{- if .Values.taf.publisher.readinessProbe }}
        readinessProbe: {{ toYaml .Values.taf.publisher.readinessProbe | nindent 10 }}
      {{- end }}
        envFrom:
        - configMapRef:
            name: {{ .Values.taf.publisher.name }}
        volumeMounts:
        - name: publisher-volume
          mountPath: {{ .Values.taf.publisher.DESTINATION | quote }}
      - name: {{ .Values.taf.nginx.name }}
        image: {{ .Values.taf.nginx.registry }}:{{ .Values.versions.taf }}
      {{- if .Values.taf.imagePullPolicy }}
        imagePullPolicy: {{ .Values.taf.imagePullPolicy }}
      {{- end }}
        ports:
        - containerPort: {{ .Values.taf.nginx.NGINX_PORT_HTTP }}
      {{- if .Values.taf.nginx.resources }}
        resources: {{ toYaml .Values.taf.nginx.resources | nindent 10 }}
      {{- end }}
      {{- if .Values.taf.nginx.livenessProbe }}
        livenessProbe: {{ toYaml .Values.taf.nginx.livenessProbe | nindent 10 }}
      {{- end }}
      {{- if .Values.taf.nginx.readinessProbe }}
        readinessProbe: {{ toYaml .Values.taf.nginx.readinessProbe | nindent 10 }}
      {{- end }}
        envFrom:
        - configMapRef:
            name: {{ .Values.taf.nginx.name }}
      {{- if .Values.taf.db.enableDefaultDb }}
      - name: {{ .Values.taf.db.name }}
        image: {{ .Values.taf.db.image }}
        ports:
          - containerPort: {{ .Values.taf.db.port }}
        env:
          - name: POSTGRES_DB
            value: {{ .Values.taf.db.POSTGRES_DB }}
          - name: POSTGRES_USER
            value: {{ .Values.taf.db.POSTGRES_USER }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.taf.db.POSTGRES_PASSWORD }}
      {{- end }}
      volumes:
      - name: secrets-store-inline
      {{- if .Values.secretProvider }}
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .Values.taf.spcName | quote }}
      {{- else }}
        secret:
          secretName: {{ .Values.taf.db_secretName | quote }}
      {{- end }}
      - name: publisher-volume
      {{- if .Values.taf.publisher.volumeOptions }}
        {{- toYaml .Values.taf.publisher.volumeOptions | nindent 8 }}
      {{- else }}
        emptyDir:
      {{- end }}