apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.taf.name }}
  annotations:
  {{- if .Values.taf.commitHash }}
    commitHash: {{ .Values.taf.commitHash }}
  {{- end }}
data:
  VERSION: {{ default .Chart.AppVersion .Values.versions.taf | quote }}
  {{- if .Values.taf.messageconverter.version }}
  AVI_VERSION: {{ .Values.taf.messageconverter.version | quote }}
  {{- end }}
  {{- range $key, $value := .Values.taf.env }}
  {{ $key | upper }}: {{ $value | quote }}
  {{- end }}
 