apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.taf.nginx.name }}
  annotations:
  {{- if .Values.taf.commitHash }}
    commitHash: {{ .Values.taf.commitHash }}
  {{- end }}
data:
{{- if .Values.taf.nginx.AVIATION_TAF_ENABLE_SSL }}
  AVIATION_TAF_ENABLE_SSL: {{ .Values.taf.nginx.AVIATION_TAF_ENABLE_SSL | quote }}
{{- end }}
{{- if .Values.taf.nginx.OAUTH2_USERINFO }}
  OAUTH2_USERINFO: {{ .Values.taf.nginx.OAUTH2_USERINFO | quote }}
{{- end }}
{{- if .Values.opmet.nginx.GEOWEB_REQUIRE_READ_PERMISSION }}
  GEOWEB_REQUIRE_READ_PERMISSION: {{ .Values.opmet.nginx.GEOWEB_REQUIRE_READ_PERMISSION | quote }}
{{- end }}
{{- if .Values.opmet.nginx.GEOWEB_REQUIRE_WRITE_PERMISSION }}
  GEOWEB_REQUIRE_WRITE_PERMISSION: {{ .Values.opmet.nginx.GEOWEB_REQUIRE_WRITE_PERMISSION | quote }}
{{- end }}
{{- if .Values.taf.nginx.AVIATION_TAF_BACKEND_HOST }}
  AVIATION_TAF_BACKEND_HOST: {{ .Values.taf.nginx.AVIATION_TAF_BACKEND_HOST | quote }}
{{- end }}
{{- if .Values.taf.nginx.NGINX_PORT_HTTP }}
  NGINX_PORT_HTTP: {{ .Values.taf.nginx.NGINX_PORT_HTTP | quote }}
{{- end }}
{{- if .Values.taf.nginx.NGINX_PORT_HTTPS }}
  NGINX_PORT_HTTPS: {{ .Values.taf.nginx.NGINX_PORT_HTTPS | quote }}
{{- end }}