-- Runs on verifapi as postgres (superuser) after the production schema and the
-- ownership transfer.
--
-- Reference data the applications require in every deployment. These are not
-- customer metadata: the names below are compiled into the GUI, so a database
-- without them yields a broken installation rather than an empty one.
--
-- target_types: TargetTypeRadioGroup preselects GROUP, then AREA, then LOCATION,
-- and leaves the radio group unset when it finds none of them. Every query form
-- then switches on the selected name, so an empty table makes the switch throw
--   Cannot invoke "String.hashCode()" because "<local>" is null
-- on the first view the user opens. Nineteen GUI classes reach that switch, so
-- the whole interface is affected, not one view.
--
-- Idempotent on purpose. The test image (Dockerfile.test) loads the same rows
-- from csv/metadata/target_types.csv in 0003-legacy-test-data.sql, which runs
-- first; without ON CONFLICT this file would abort that build on the unique
-- name index.

INSERT INTO public.target_types (id, name)
VALUES (1, 'LOCATION'),
       (2, 'GROUP'),
       (3, 'AREA')
ON CONFLICT DO NOTHING;

-- The id column defaults to nextval() on this sequence. The rows above set ids
-- explicitly, which does not advance it, so without this a later insert that
-- omits the id would collide with id 1.
SELECT setval('public.target_types_id_seq', (SELECT max(id) FROM public.target_types));

-- ---------------------------------------------------------------------------
-- estimators, and the localized descriptions they hang off
-- ---------------------------------------------------------------------------
--
-- The 97 estimators FMI verifies with. Like target_types these are not
-- customer metadata: the GUI compiles both estimator names and estimator ids
-- into its source, so the ids below are fixed and a deployment that renumbers
-- them gets views that quietly show nothing.
--
-- BIAS_ON_MAP is the sharpest case. ColumnDiagramChartBuilder hardcodes id 93
-- while EstimatorComboBox looks the same row up by name, so the two agree only
-- when id 93 is the row named BIAS_ON_MAP. With the row missing altogether that
-- combo box calls findFirst() on a one-element list holding null and throws,
-- which is what made the bias-on-map view an Internal Server Error page before
-- fmi-verification-gui 3.25.1.
--
-- scale is how many decimals the GUI renders a value with, and it is NOT NULL:
-- Estimator.getScale() dereferences it unconditionally. ColorUtils derives map
-- legend limits from scale - 1, so 0 rounds those limits to tens.
--
-- character is read by the runner, not the GUI. Only SSC, SSP, SEEPS, EPOCH and
-- CATEGORY change behaviour; everything else takes the default branch.
--
-- Insert order is load-bearing, and follows the foreign keys:
-- localization_languages and localization_entries first, then estimators
-- (estimators.description_id references an entry), then the translations
-- (which reference both an entry and a language).

-- Language ids match FMI's so that translations synced from there later line up.
-- Swedish carries no estimator descriptions at FMI either; the row exists so the
-- id is not taken by something else.
INSERT INTO public.localization_languages (id, code, description)
VALUES (1, 'en', 'English'),
       (2, 'fi', 'Finnish'),
       (3, 'sv', 'Swedish')
ON CONFLICT DO NOTHING;

-- One entry per estimator description. FMI's own entry ids are scattered through
-- a table it shares with parameters, producers and target groups; here they are
-- renumbered to equal the estimator they describe, which is also what entity_id
-- holds. Nothing outside this file refers to an entry id, so the renumbering is
-- safe and makes the three blocks below readable together.
INSERT INTO public.localization_entries (id, tablename, columnname, entity_id)
VALUES
       (1, 'estimators', 'description_id', 1),
       (2, 'estimators', 'description_id', 2),
       (3, 'estimators', 'description_id', 3),
       (4, 'estimators', 'description_id', 4),
       (5, 'estimators', 'description_id', 5),
       (6, 'estimators', 'description_id', 6),
       (7, 'estimators', 'description_id', 7),
       (8, 'estimators', 'description_id', 8),
       (9, 'estimators', 'description_id', 9),
       (10, 'estimators', 'description_id', 10),
       (11, 'estimators', 'description_id', 11),
       (12, 'estimators', 'description_id', 12),
       (13, 'estimators', 'description_id', 13),
       (14, 'estimators', 'description_id', 14),
       (15, 'estimators', 'description_id', 15),
       (16, 'estimators', 'description_id', 16),
       (17, 'estimators', 'description_id', 17),
       (18, 'estimators', 'description_id', 18),
       (19, 'estimators', 'description_id', 19),
       (20, 'estimators', 'description_id', 20),
       (21, 'estimators', 'description_id', 21),
       (22, 'estimators', 'description_id', 22),
       (23, 'estimators', 'description_id', 23),
       (24, 'estimators', 'description_id', 24),
       (25, 'estimators', 'description_id', 25),
       (26, 'estimators', 'description_id', 26),
       (27, 'estimators', 'description_id', 27),
       (28, 'estimators', 'description_id', 28),
       (29, 'estimators', 'description_id', 29),
       (30, 'estimators', 'description_id', 30),
       (31, 'estimators', 'description_id', 31),
       (32, 'estimators', 'description_id', 32),
       (33, 'estimators', 'description_id', 33),
       (34, 'estimators', 'description_id', 34),
       (35, 'estimators', 'description_id', 35),
       (36, 'estimators', 'description_id', 36),
       (37, 'estimators', 'description_id', 37),
       (38, 'estimators', 'description_id', 38),
       (39, 'estimators', 'description_id', 39),
       (40, 'estimators', 'description_id', 40),
       (41, 'estimators', 'description_id', 41),
       (42, 'estimators', 'description_id', 42),
       (43, 'estimators', 'description_id', 43),
       (44, 'estimators', 'description_id', 44),
       (45, 'estimators', 'description_id', 45),
       (46, 'estimators', 'description_id', 46),
       (47, 'estimators', 'description_id', 47),
       (48, 'estimators', 'description_id', 48),
       (49, 'estimators', 'description_id', 49),
       (50, 'estimators', 'description_id', 50),
       (51, 'estimators', 'description_id', 51),
       (52, 'estimators', 'description_id', 52),
       (53, 'estimators', 'description_id', 53),
       (54, 'estimators', 'description_id', 54),
       (55, 'estimators', 'description_id', 55),
       (56, 'estimators', 'description_id', 56),
       (57, 'estimators', 'description_id', 57),
       (58, 'estimators', 'description_id', 58),
       (59, 'estimators', 'description_id', 59),
       (60, 'estimators', 'description_id', 60),
       (61, 'estimators', 'description_id', 61),
       (62, 'estimators', 'description_id', 62),
       (63, 'estimators', 'description_id', 63),
       (64, 'estimators', 'description_id', 64),
       (65, 'estimators', 'description_id', 65),
       (66, 'estimators', 'description_id', 66),
       (67, 'estimators', 'description_id', 67),
       (68, 'estimators', 'description_id', 68),
       (69, 'estimators', 'description_id', 69),
       (70, 'estimators', 'description_id', 70),
       (71, 'estimators', 'description_id', 71),
       (72, 'estimators', 'description_id', 72),
       (73, 'estimators', 'description_id', 73),
       (74, 'estimators', 'description_id', 74),
       (78, 'estimators', 'description_id', 78),
       (79, 'estimators', 'description_id', 79),
       (80, 'estimators', 'description_id', 80),
       (81, 'estimators', 'description_id', 81),
       (82, 'estimators', 'description_id', 82),
       (83, 'estimators', 'description_id', 83),
       (85, 'estimators', 'description_id', 85),
       (87, 'estimators', 'description_id', 87),
       (90, 'estimators', 'description_id', 90),
       (93, 'estimators', 'description_id', 93),
       (94, 'estimators', 'description_id', 94),
       (95, 'estimators', 'description_id', 95),
       (96, 'estimators', 'description_id', 96),
       (97, 'estimators', 'description_id', 97),
       (98, 'estimators', 'description_id', 98),
       (101, 'estimators', 'description_id', 101),
       (102, 'estimators', 'description_id', 102),
       (103, 'estimators', 'description_id', 103),
       (104, 'estimators', 'description_id', 104),
       (105, 'estimators', 'description_id', 105),
       (106, 'estimators', 'description_id', 106),
       (107, 'estimators', 'description_id', 107),
       (110, 'estimators', 'description_id', 110)
ON CONFLICT DO NOTHING;

-- description_id points at the entry created above, so it equals the estimator id.
INSERT INTO public.estimators (id, name, description_id, minimum_value, maximum_value, scale, "character")
VALUES
       (1, 'ME', 1, NULL, NULL, 2, 'CONTINUOUS'),
       (2, 'MAE', 2, 0.0, NULL, 2, 'CONTINUOUS'),
       (3, 'RMSE', 3, 0.0, NULL, 2, 'CONTINUOUS'),
       (4, 'MSE', 4, 0.0, NULL, 2, 'CONTINUOUS'),
       (5, 'VAR', 5, 0.0, NULL, 2, 'CONTINUOUS'),
       (6, 'SD', 6, 0.0, NULL, 2, 'CONTINUOUS'),
       (7, 'SSC', 7, NULL, 1.0, 3, 'SSC'),
       (8, 'SSP', 8, NULL, 1.0, 3, 'SSP'),
       (9, 'CC', 9, -1.0, 1.0, 3, 'CONTINUOUS'),
       (10, 'HR', 10, 0.0, 1.0, 3, 'CONTINUOUS'),
       (11, 'HR3', 11, 0.0, 1.0, 3, 'CONTINUOUS'),
       (12, 'FBIAS', 12, 0.0, NULL, 3, 'CATEGORY'),
       (13, 'MBIAS', 13, 0.0, NULL, 3, 'CONTINUOUS'),
       (14, 'MINE', 14, NULL, NULL, 1, 'CONTINUOUS'),
       (15, 'MAXE', 15, NULL, NULL, 1, 'CONTINUOUS'),
       (16, 'MEDE', 16, NULL, NULL, 1, 'CONTINUOUS'),
       (17, 'BS', 17, 0.0, 1.0, 3, 'PROBABILITY'),
       (18, 'ROC', 18, 0.0, 1.0, 3, 'PROBABILITY'),
       (19, 'ETS', 19, -0.334, 1.0, 3, 'CATEGORY'),
       (20, 'EDS', 20, -1.0, 1.0, 3, 'CATEGORY'),
       (21, 'EDI', 21, -1.0, 1.0, 3, 'CATEGORY'),
       (22, 'SEDI', 22, -1.0, 1.0, 3, 'CATEGORY'),
       (23, 'SEDS', 23, -1.0, 1.0, 3, 'CATEGORY'),
       (24, 'FAR', 24, 0.0, 1.0, 3, 'CATEGORY'),
       (25, 'POD', 25, 0.0, 1.0, 3, 'CATEGORY'),
       (26, 'POFD', 26, 0.0, 1.0, 3, 'CATEGORY'),
       (27, 'PC', 27, 0.0, 1.0, 3, 'CATEGORY'),
       (28, 'HSS', 28, -1.0, 1.0, 3, 'CATEGORY'),
       (29, 'KSS', 29, -1.0, 1.0, 3, 'CATEGORY'),
       (30, 'OR', 30, 0.0, NULL, 3, 'CATEGORY'),
       (31, 'ORSS', 31, -1.0, 1.0, 3, 'CATEGORY'),
       (32, 'PAG', 32, 0.0, 1.0, 3, 'CATEGORY'),
       (33, 'TS', 33, 0.0, 1.0, 3, 'CATEGORY'),
       (34, 'SEEPS', 34, 0.0, NULL, 3, 'SEEPS'),
       (35, 'SEEPS_13', 35, 0.0, NULL, 3, 'SEEPS'),
       (36, 'SEEPS_23', 36, 0.0, NULL, 3, 'SEEPS'),
       (37, 'SEEPS_12', 37, 0.0, NULL, 3, 'SEEPS'),
       (38, 'SEEPS_32', 38, 0.0, NULL, 3, 'SEEPS'),
       (39, 'SEEPS_21', 39, 0.0, NULL, 3, 'SEEPS'),
       (40, 'SEEPS_31', 40, 0.0, NULL, 3, 'SEEPS'),
       (41, 'COUNT', 41, 0, NULL, 0, 'CATEGORY'),
       (42, 'RPS', 42, 0.0, 1.0, 3, 'PROBABILITY'),
       (43, 'INDEXHR3_M', 43, 0.0, 1.0, 3, 'INDEX'),
       (44, 'INDEXHR3', 44, 0.0, 1.0, 3, 'INDEX'),
       (45, 'EPOCH', 45, 0, NULL, 0, 'EPOCH'),
       (46, 'INDEXME', 46, NULL, NULL, 2, 'INDEX'),
       (47, 'INDEXMAE', 47, 0, NULL, 2, 'INDEX'),
       (48, 'RVM_M', 48, -1.0, 1.0, 3, 'RVM'),
       (49, 'RVM', 49, -1.0, 1.0, 3, 'RVM'),
       (50, 'ROC2', 50, 0.0, 1.0, 3, 'CATEGORY'),
       (51, 'INDEXKSS', 51, -1.0, 1.0, 3, 'INDEX'),
       (52, 'INDEXRMSE', 52, 0, NULL, 2, 'INDEX'),
       (53, 'INDEXSEEPS', 53, 0, NULL, 3, 'INDEX'),
       (54, 'INDEXMBIAS', 54, 0.0, NULL, 3, 'INDEX'),
       (55, 'INDEXETS', 55, -0.334, 1.0, 3, 'INDEX'),
       (56, 'A', 56, 0, NULL, 0, 'CATEGORY'),
       (57, 'B', 57, 0, NULL, 0, 'CATEGORY'),
       (58, 'C', 58, 0, NULL, 0, 'CATEGORY'),
       (59, 'D', 59, 0, NULL, 0, 'CATEGORY'),
       (60, 'INDEXROC2', 60, 0.0, 1.0, 3, 'INDEX'),
       (61, 'INDEXFAR', 61, 0.0, 1.0, 3, 'INDEX'),
       (62, 'INDEXPOD', 62, 0.0, 1.0, 3, 'INDEX'),
       (63, 'PREDICTABILITY', 63, 0.0, NULL, 1, 'PREDICTABILITY'),
       (64, 'ZLPOD_DOWN', 64, 0.0, 1.0, 3, 'ZL'),
       (65, 'ZLPOD_UP', 65, 0.0, 1.0, 3, 'ZL'),
       (66, 'ZLPOD', 66, 0.0, 1.0, 3, 'ZL'),
       (67, 'RF', 67, 0.0, 1.0, 3, 'CONTINUOUS'),
       (68, 'INDEXHR3_C', 68, 0.0, 1.0, 3, 'INDEX'),
       (69, 'RVM_C', 69, -1.0, 1.0, 3, 'RVM'),
       (70, 'INDEXEPOCH', 70, NULL, NULL, 0, 'INDEX'),
       (71, 'ZLTME_DOWN', 71, NULL, NULL, 3, 'ZL'),
       (72, 'ZLTME_UP', 72, NULL, NULL, 3, 'ZL'),
       (73, 'ZLTME', 73, NULL, NULL, 3, 'ZL'),
       (74, 'ZLBIAS', 74, NULL, NULL, 3, 'ZL'),
       (78, 'ZLTSD_DOWN', 78, 0.0, NULL, 3, 'ZL'),
       (79, 'ZLTSD_UP', 79, 0.0, NULL, 3, 'ZL'),
       (80, 'ZLTSD', 80, 0.0, NULL, 3, 'ZL'),
       (81, 'ZLFAR_DOWN', 81, 0.0, 1.0, 3, 'ZL'),
       (82, 'ZLFAR_UP', 82, 0.0, 1.0, 3, 'ZL'),
       (83, 'ZLFAR', 83, 0.0, 1.0, 3, 'ZL'),
       (85, 'ZLHR', 85, 0.0, 1.0, 3, 'ZL'),
       (87, 'ZLROC2', 87, 0.0, 1.0, 3, 'ZL'),
       (90, 'SCORE', 90, 0.0, 100.0, 0, 'SCORE'),
       (93, 'BIAS_ON_MAP', 93, NULL, NULL, 2, 'GUI'),
       (94, 'IGNS', 94, 0.0, NULL, 3, 'PROBABILITY'),
       (95, 'FSS', 95, 0.0, 1.0, 3, 'AREA'),
       (96, 'BTS', 96, -1.0, 1.0, 3, 'CATEGORY'),
       (97, 'EER', 97, 0.0, NULL, 3, 'CATEGORY'),
       (98, 'F1SCORE', 98, 0.0, 1.0, 3, 'CATEGORY'),
       (101, 'INDEXME_TMIN', 101, NULL, NULL, 2, 'INDEX'),
       (102, 'INDEXME_TMAX', 102, NULL, NULL, 2, 'INDEX'),
       (103, 'INDEXRMSE_TMAX', 103, NULL, NULL, 2, 'INDEX'),
       (104, 'INDEXRMSE_TMIN', 104, NULL, NULL, 2, 'INDEX'),
       (105, 'DIURNAL_CYCLE', 105, NULL, NULL, 2, 'DC'),
       (106, 'INDEXME_BETA', 106, NULL, NULL, 2, 'INDEX'),
       (107, 'INDEXRMSE_BETA', 107, NULL, NULL, 2, 'INDEX'),
       (110, 'RDS', 110, 0.0, 1.0, 3, 'AREA')
ON CONFLICT DO NOTHING;

-- English and Finnish, the two languages FMI has estimator descriptions in.
-- Without these the GUI still runs and its combo boxes still show the estimator
-- name, but chart titles and series names fall back to the numeric id, so a
-- series reads "1" rather than "mean error".
INSERT INTO public.localization_translations (entry_id, language_id, translation)
VALUES
       (1, 1, 'mean error'),
       (2, 1, 'mean absolute error'),
       (3, 1, 'root mean square error'),
       (4, 1, 'mean square error'),
       (5, 1, 'variance'),
       (6, 1, 'standard deviation'),
       (7, 1, 'climatology skill score'),
       (8, 1, 'persistence skill score'),
       (9, 1, 'correlation coefficient'),
       (10, 1, 'hit rate (HR)'),
       (11, 1, 'hit rate (HR3)'),
       (12, 1, 'frequency bias'),
       (13, 1, 'multiplicative bias'),
       (14, 1, 'minimum error'),
       (15, 1, 'maximum error'),
       (16, 1, 'median error'),
       (17, 1, 'Brier score'),
       (18, 1, 'relative operating characteristic'),
       (19, 1, 'equitable threat score'),
       (20, 1, 'extreme dependency score'),
       (21, 1, 'extremal dependency index'),
       (22, 1, 'symmetric extremal dependency index'),
       (23, 1, 'symmetric extreme depedency score'),
       (24, 1, 'false alarm ratio'),
       (25, 1, 'probability of detection'),
       (26, 1, 'probability of false detection'),
       (27, 1, 'proportion correct'),
       (28, 1, 'Heidke skill score'),
       (29, 1, 'Kuipers skill score'),
       (30, 1, 'odds ratio'),
       (31, 1, 'odds ratio skill score'),
       (32, 1, 'post agreement'),
       (33, 1, 'threat score'),
       (34, 1, 'stable equitable error in probability space'),
       (35, 1, 'SEEPS_F103'),
       (36, 1, 'SEEPS_F203'),
       (37, 1, 'SEEPS_F102'),
       (38, 1, 'SEEPS_F302'),
       (39, 1, 'SEEPS_F201'),
       (40, 1, 'SEEPS_F301'),
       (41, 1, 'count'),
       (42, 1, 'Ranked probability score'),
       (43, 1, 'hr3 index (min/max)'),
       (44, 1, 'hr3 index'),
       (45, 1, 'epoch time'),
       (46, 1, 'index me'),
       (47, 1, 'index mae'),
       (48, 1, 'reference value of the meteorologist (min/max)'),
       (49, 1, 'reference value of the meteorologist'),
       (50, 1, 'relative operating characteristic 2'),
       (51, 1, 'index kss'),
       (52, 1, 'index rmse'),
       (53, 1, 'index seeps'),
       (54, 1, 'index mbias'),
       (55, 1, 'index ets'),
       (56, 1, 'hit count'),
       (57, 1, 'false alarm count'),
       (58, 1, 'miss count'),
       (59, 1, 'correct negatives'),
       (60, 1, 'index roc2'),
       (61, 1, 'index far'),
       (62, 1, 'index pod'),
       (63, 1, 'predictability'),
       (64, 1, 'zero limit pass downward POD'),
       (65, 1, 'zero limit pass upward POD'),
       (66, 1, 'zero limit pass POD'),
       (67, 1, 'relative frequency'),
       (68, 1, 'hr3 index (inst/min/max)'),
       (69, 1, 'reference value of the meteorologist (inst/min/max)'),
       (70, 1, 'epoch index'),
       (71, 1, 'zero limit pass downward time ME'),
       (72, 1, 'zero limit pass upward time ME'),
       (73, 1, 'zero limit pass time ME'),
       (74, 1, 'zero limit BIAS'),
       (78, 1, 'zero limit pass downward time SD'),
       (79, 1, 'zero limit pass upward time SD'),
       (80, 1, 'zero limit pass time SD'),
       (81, 1, 'zero limit pass downward FAR'),
       (82, 1, 'zero limit pass upward FAR'),
       (83, 1, 'zero limit pass FAR'),
       (85, 1, 'zero limit HR'),
       (87, 1, 'zero limit pass ROC2'),
       (90, 1, 'aviation score'),
       (93, 1, 'bias on map'),
       (94, 1, 'ignorance score'),
       (95, 1, 'fractions skill score'),
       (96, 1, 'balanced threat score'),
       (97, 1, 'extreme event odds ratio'),
       (98, 1, 'F1-score'),
       (101, 1, 'me index t min'),
       (102, 1, 'me index t max'),
       (103, 1, 'rmse index t max'),
       (104, 1, 'rmse index t min'),
       (105, 1, 'diurnal cycle'),
       (106, 1, 'ME index aggregated by 24 h leadtime blocks'),
       (107, 1, 'RMSE index aggregated by 24 h leadtime blocks'),
       (110, 1, 'rainfall distribution similarity'),
       (1, 2, 'keskivirhe'),
       (2, 2, 'absoluuttinen keskivirhe'),
       (3, 2, 'neliöllisen keskivirheen neliöjuuri'),
       (4, 2, 'neliöllinen keskivirhe'),
       (5, 2, 'varianssi'),
       (6, 2, 'keskihajonta'),
       (7, 2, 'climatology skill score'),
       (8, 2, 'persistence skill score'),
       (9, 2, 'korrelaatiokerroin'),
       (10, 2, 'osuvuus (HR)'),
       (11, 2, 'osuvuus (HR3)'),
       (12, 2, 'frekvenssibias'),
       (13, 2, 'kertymäbias'),
       (14, 2, 'minimivirhe'),
       (15, 2, 'maksimivirhe'),
       (16, 2, 'mediaanivirhe'),
       (17, 2, 'Brier score'),
       (18, 2, 'relative operating characteristic'),
       (19, 2, 'equitable threat score'),
       (20, 2, 'extreme dependency score'),
       (21, 2, 'extremal dependency index'),
       (22, 2, 'symmetric extremal dependency index'),
       (23, 2, 'symmetric extreme depedency score'),
       (24, 2, 'väärien hälytysten osuus'),
       (25, 2, 'hälytysten osuvuus'),
       (26, 2, 'väärien hälytysten poikkeamaosuvuus'),
       (27, 2, 'tarkkojen ennusteiden osuus'),
       (28, 2, 'Heidke skill score'),
       (29, 2, 'Kuipers skill score'),
       (30, 2, 'odds ratio'),
       (31, 2, 'odds ratio skill score'),
       (32, 2, 'post agreement'),
       (33, 2, 'threat score'),
       (34, 2, 'stable equitable error in probability space'),
       (35, 2, 'SEEPS_E1H3'),
       (36, 2, 'SEEPS_E2H3'),
       (37, 2, 'SEEPS_E1H2'),
       (38, 2, 'SEEPS_E3H2'),
       (39, 2, 'SEEPS_E2H1'),
       (40, 2, 'SEEPS_E3H1'),
       (41, 2, 'lukumäärä'),
       (42, 2, 'Ranked probability score'),
       (43, 2, 'hr3 indeksi (min/max)'),
       (44, 2, 'hr3 indeksi'),
       (45, 2, 'epookki aika'),
       (46, 2, 'me indeksi'),
       (47, 2, 'mae indeksi'),
       (48, 2, 'meteorologin vertailuarvo (min/max)'),
       (49, 2, 'meteorologin vertailuarvo'),
       (50, 2, 'relative operating characteristic 2'),
       (51, 2, 'kss indeksi'),
       (52, 2, 'rmse indeksi'),
       (53, 2, 'seeps indeksi'),
       (54, 2, 'mbias indeksi'),
       (55, 2, 'ets indeksi'),
       (56, 2, 'lukumäärä, ennustettu ja havaittu'),
       (57, 2, 'lukumäärä, ennustettu ja ei havaittu'),
       (58, 2, 'lukumäärä, ei ennustettu ja havaittu'),
       (59, 2, 'lukumäärä, ei ennustettu ja ei havaittu'),
       (60, 2, 'roc2 indeksi'),
       (61, 2, 'far indeksi'),
       (62, 2, 'pod indeksi'),
       (63, 2, 'ennustettavuus'),
       (64, 2, '0-rajan alitus POD'),
       (65, 2, '0-rajan ylitys POD'),
       (66, 2, '0-rajan läpäisy POD'),
       (67, 2, 'osuvuusfrekvenssi'),
       (68, 2, 'hr3 indeksi (inst/min/max)'),
       (69, 2, 'meteorologin vertailuarvo (inst/min/max)'),
       (70, 2, 'epookki indeksi'),
       (71, 2, '0-rajan alitusaika ME'),
       (72, 2, '0-rajan ylitysaika ME'),
       (73, 2, '0-rajan läpäisyaika ME'),
       (74, 2, '0-rajan BIAS'),
       (78, 2, '0-rajan alitusaika SD'),
       (79, 2, '0-rajan ylitysaika SD'),
       (80, 2, '0-rajan läpäisyaika SD'),
       (81, 2, '0-rajan alitus FAR'),
       (82, 2, '0-rajan ylitys FAR'),
       (83, 2, '0-rajan läpäisy FAR'),
       (85, 2, '0-rajan HR'),
       (87, 2, '0-rajan läpäisy ROC2'),
       (90, 2, 'lentopisteytys'),
       (93, 2, 'bias kartalla'),
       (94, 2, 'ignorance score'),
       (95, 2, 'fractions skill score'),
       (96, 2, 'balanced threat score'),
       (97, 2, 'extreme event odds ratio'),
       (98, 2, 'F1-score'),
       (101, 2, 'me indeksi t min'),
       (102, 2, 'me indeksi t max'),
       (103, 2, 'rmse indeksi t max'),
       (104, 2, 'rmse indeksi t min'),
       (105, 2, 'vuorokausvaihtelu'),
       (106, 2, 'ME-indeksi, koottu 24 tunnin ennustepituuslohkoista'),
       (107, 2, 'INDEXRMSE-indeksi, koottu 24 tunnin ennustepituuslohkoista'),
       (110, 2, 'sademääräjakauman samankaltaisuus')
ON CONFLICT DO NOTHING;

-- Both id columns default to nextval() on these sequences, and the explicit ids
-- above do not advance them. Same reasoning as target_types_id_seq.
SELECT setval('public.localization_languages_id_seq', (SELECT max(id) FROM public.localization_languages));
SELECT setval('public.localization_entries_id_seq', (SELECT max(id) FROM public.localization_entries));
SELECT setval('public.estimators_id_seq', (SELECT max(id) FROM public.estimators));
