apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.smartmetserver.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.smartmetserver.name }}
spec:
  replicas: {{ .Values.smartmetserver.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.smartmetserver.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.smartmetserver.name }}
    spec:
      containers:
      - name: {{.Values.smartmetserver.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
      {{- if .Values.image.pullPolicy }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      {{- end }}
        ports:
        - containerPort: {{ .Values.smartmetserver.containerPort }}
        volumeMounts:
        - mountPath: "/smartmet/data"
          name: smartmetserver-volume
      volumes:
      - name: smartmetserver-volume
      {{- if .Values.pvc }}
        persistentVolumeClaim:
          claimName: {{ .Values.smartmetserver.name }}-{{ .Values.pvc.name }}
      {{- else}}
        emptyDir: {}
      {{- end }}
