apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.smartmetserver.name }}
  labels:
    app: {{ .Values.smartmetserver.name }}
spec:
  replicas: {{ .Values.smartmetserver.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.smartmetserver.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.smartmetserver.name }}
    spec:
      containers:
      - name: {{.Values.smartmetserver.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        {{- if .Values.image.pullPolicy }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.smartmetserver.containerPort }}
        volumeMounts:
        - mountPath: "/smartmet/data"
          name: smartmetserver-volume
        livenessProbe:
          httpGet:
            path: /admin?what=qengine
            port: {{ .Values.smartmetserver.containerPort }}
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /admin?what=qengine
            port: {{ .Values.smartmetserver.containerPort }}
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /admin?what=qengine
            port: {{ .Values.smartmetserver.containerPort }}
          failureThreshold: 3
          periodSeconds: 10
      volumes:
      - name: smartmetserver-volume
        persistentVolumeClaim:
          claimName: {{ .Values.smartmetserver.name }}-{{ .Values.pvc.name }}
