apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smartmetserver.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "smartmetserver.labels.component" (merge (dict "component" "application") .) | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.smartmetserver.replicas }}
  selector:
    matchLabels:
      {{- include "smartmetserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "smartmetserver.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "smartmetserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext.pod | nindent 8 }}
      containers:
      - name: {{.Values.smartmetserver.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        {{- if .Values.image.pullPolicy }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- end }}
        command: ["/usr/sbin/smartmetd"]
        securityContext:
          {{- toYaml .Values.securityContext.container | nindent 10 }}
        ports:
        - containerPort: {{ .Values.smartmetserver.containerPort }}
        volumeMounts:
        - mountPath: "/smartmet/data"
          name: smartmetserver-volume
          readOnly: {{ .Values.volume.readOnly }}
        - mountPath: "/etc/smartmet/smartmet.conf"
          subPath: "smartmet.conf"
          name: smartmet-configuration
        - mountPath: "/var/smartmet/cache"
          name: cache-volume
        - mountPath: "/var/smartmet/archivecache"
          name: archivecache-volume
        - mountPath: "/etc/smartmet/engines/querydata.conf"
          subPath: "querydata.conf"
          name: smartmet-querydata-config
        livenessProbe:
          tcpSocket:
            port: {{ .Values.smartmetserver.containerPort }}
          initialDelaySeconds: {{ .Values.smartmetserver.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.smartmetserver.livenessProbe.periodSeconds }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.smartmetserver.containerPort }}
          initialDelaySeconds: {{ .Values.smartmetserver.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.smartmetserver.readinessProbe.periodSeconds }}
          failureThreshold: {{ .Values.smartmetserver.readinessProbe.failureThreshold }}
        startupProbe:
          tcpSocket:
            port: {{ .Values.smartmetserver.containerPort }}
          initialDelaySeconds: {{ .Values.smartmetserver.startupProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.smartmetserver.startupProbe.periodSeconds }}
          failureThreshold: {{ .Values.smartmetserver.startupProbe.failureThreshold }}
        {{- if .Values.smartmetserver.resources }}
        resources:
          {{- toYaml .Values.smartmetserver.resources | nindent 10 }}
        {{- end }}
      volumes:
      - name: smartmetserver-volume
        {{- if eq .Values.volume.type "cephfs" }}
        persistentVolumeClaim:
          claimName: {{ .Values.volume.cephfs.pvc.name }}
        {{- else if eq .Values.volume.type "nfs" }}
        nfs:
          server: {{ .Values.volume.nfs.server }}
          path: {{ .Values.volume.nfs.path }}
          readOnly: {{ .Values.volume.readOnly }}
        {{- else if eq .Values.volume.type "hostPath" }}
        persistentVolumeClaim:
          claimName: {{ .Values.volume.hostPath.pvc.name }}
        {{- else }}
        {{- fail "volume.type must be one of: cephfs, nfs, hostPath" }}
        {{- end }}
      - name: smartmet-configuration
        configMap:
          name: {{ include "smartmetserver.fullname" . }}-config
      - name: smartmet-querydata-config
        configMap:
          name: {{ include "smartmetserver.fullname" . }}-querydata-config
      - name: cache-volume
        emptyDir: {}
      - name: archivecache-volume
        emptyDir: {}
