apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.smartmetserver.name }}-{{ .Values.gisConfCm.name }}
  labels:
    app: {{ .Values.smartmetserver.name }}
  namespace: {{ .Release.Namespace }}
data:
  gis.conf: |
    {{- .Values.gisConfCm.gisConf | nindent 4 }}
