apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "smartmetserver.fullname" . }}-hpa
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "smartmetserver.labels.component" (dict "Chart" .Chart "Release" .Release "Values" .Values "component" "autoscaling") | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "smartmetserver.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.targetCPUUtilizationPercentage }}
    {{- if .Values.hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.targetMemoryUtilizationPercentage }}
    {{- end }}
  {{- if .Values.hpa.behavior }}
  behavior:
    {{- if .Values.hpa.behavior.scaleDown }}
    scaleDown:
      {{- toYaml .Values.hpa.behavior.scaleDown | nindent 6 }}
    {{- end }}
    {{- if .Values.hpa.behavior.scaleUp }}
    scaleUp:
      {{- toYaml .Values.hpa.behavior.scaleUp | nindent 6 }}
    {{- end }}
  {{- end }}
