{{- if .Values.ingress.enabled }}
{{- if not .Values.ingress.hosts }}
{{- fail "ingress.hosts must be provided when ingress is enabled" }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "smartmetserver.fullname" . }}-ingress
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "smartmetserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingress
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.ingress.tls.issuerRef }}
    cert-manager.io/{{ .kind | lower }}: {{ .name | quote }}
    {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}

  {{- if and .Values.ingress.tls.enabled .Values.ingress.hosts }}
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .Values.ingress.tls.secretName | quote }}
  {{- end }}

  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          {{- range $.Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $.Values.smartmetserver.name }}
                port:
                  number: {{ $.Values.smartmetserver.svcPort }}
          {{- end }}
    {{- end }}
{{- end }}