apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.smartmetserver.name }}-init-sh
  labels:
    app: {{ .Values.smartmetserver.name }}
  namespace: {{ .Release.Namespace }}
data:
  insert_geonames.sh: |
    #!/usr/bin/env bash
    set -e
    
    POSTGRES_DB='names'
    
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE TEMPORARY TABLE temp_geoname (
       geonameid	int,
       name varchar(200),
       asciiname varchar(200),
       alternatenames text,
       latitude float,
       longitude float,
       fclass char(1),
       fcode varchar(10),
       country varchar(2),
       cc2 varchar(60),
       admin1 varchar(20),
       admin2 varchar(80),
       admin3 varchar(20),
       admin4 varchar(20),
       population bigint,
       elevation int,
       dem int,
       timezone varchar(40),
       moddate date
    );
    
    COPY temp_geoname (
       geonameid,
       name,
       asciiname,
       alternatenames,
       latitude,
       longitude,
       fclass,
       fcode,
       country,
       cc2,
       admin1,
       admin2,
       admin3,
       admin4,
       population,
       elevation,
       dem,
       timezone,
       moddate
    )
    FROM '/workdir/FI.txt' NULL as '';
    
    INSERT INTO public.geonames (
       id,
       "name",
       ansiname,
       lat,
       lon,
       "class",
       features_code,
       countries_iso2,
       cc2,
       admin1,
       admin2,
       admin3,
       admin4,
       population,
       elevation,
       dem,
       timezone,
       modified
    )
    SELECT
       geonameid,
       name,
       asciiname,
       latitude,
       longitude,
       fclass,
       fcode,
       country,
       cc2,
       admin1,
       admin2,
       admin3,
       admin4,
       population,
       elevation,
       dem,
       timezone,
       moddate
    FROM temp_geoname;
    
    DROP TABLE temp_geoname;
    EOSQL
    
