apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.smartmetserver.name }}-{{ .Values.postgres.name }}
spec:
  selector:
    app: {{ .Values.smartmetserver.name }}-{{ .Values.postgres.name }}
  ports:
    - port: {{ .Values.postgres.svcPort }}
      targetPort: {{ .Values.postgres.containerPort }}
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.smartmetserver.name }}-{{ .Values.postgres.name }}
  labels:
    app: {{ .Values.smartmetserver.name }}-{{ .Values.postgres.name }}
spec:
  serviceName: {{ .Values.smartmetserver.name }}-{{ .Values.postgres.name }}
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.smartmetserver.name }}-{{ .Values.postgres.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.smartmetserver.name }}-{{ .Values.postgres.name }}
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgres.image }}
        {{- if .Values.postgres.pullPolicy }}
        imagePullPolicy: {{ .Values.postgres.pullPolicy }}
        {{- end }}
        env:
          - name: POSTGRES_PASSWORD
            value: gis_pw
          - name: POSTGRES_USER
            value: gis_user
        ports:
          - containerPort: {{ .Values.postgres.containerPort }}
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgres-volume
        - mountPath: "/docker-entrypoint-initdb.d/init.sql"
          subPath: "init.sql"
          name: initsql-cm
      volumes:
      - name: postgres-volume
        persistentVolumeClaim:
          claimName: {{ .Values.postgres.name }}-{{ .Values.postgrespvc.name }}
      - name: initsql-cm
        configMap:
          name: {{ .Values.smartmetserver.name }}-init-sql
