{{- if and (not .Values.postgres.external) .Values.postgres.pv.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.name }}-{{ .Values.postgres.pvc.name }}
spec:
  storageClassName: {{ .Values.postgres.pvc.storageClassName }}
  accessModes:
    - {{ .Values.postgres.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.postgres.pvc.storage }}
{{- end }}
