apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.smartmetserver.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Values.smartmetserver.name }}
  ports: 
    - protocol: TCP
      port: {{ .Values.smartmetserver.svcPort }}
      targetPort: {{ .Values.smartmetserver.containerPort }}
