apiVersion: v1
kind: Service
metadata:
  name: {{ include "smartmetserver.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "smartmetserver.labels.component" (dict "Chart" .Chart "Release" .Release "Values" .Values "component" "network") | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "smartmetserver.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.service.portName | default "http" }}
      protocol: TCP
      port: {{ .Values.smartmetserver.svcPort }}
      targetPort: {{ .Values.service.targetPort | default .Values.smartmetserver.containerPort }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- end }}
