apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smartmetserver.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "smartmetserver.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: configuration
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
data:
  smartmet.conf: |
    {{- .Values.smartmetConfCm.smartmetConf | nindent 4 }}
