{{ if eq .Values.cloud "aws" -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.s3.credentials.name }}
        objectType: secretsmanager
        jmesPath:
          - path: S3_ACCESS_KEY_ID
            objectAlias: accessKey
          - path: S3_SECRET_ACCESS_KEY
            objectAlias: secretAccessKey
  secretObjects: # map secrets from aws secret storage to kubernetes secrets
  - data:
    - key: S3_ACCESS_KEY_ID
      objectName: accessKey
    - key: S3_SECRET_ACCESS_KEY
      objectName: secretAccessKey
    secretName: {{ .Values.s3.credentials.name }}
    type: Opaque
{{- end }}
