apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}-{{ .Values.presets.name }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "DELETE, PUT, GET, POST, OPTIONS, PATCH, HEAD"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.presets.url }}
      http:
        paths:
          - path: {{ .Values.presets.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.presets.name }}
                port:
                  number: {{ .Values.presets.svcPort }}