{{- $dbUsesAws := and (eq .Values.presets.db.mode "external") (eq .Values.presets.db.external.source "secretProvider") (eq .Values.presets.db.external.secretProvider.provider "aws") }}
{{- if $dbUsesAws }}
{{- if not .Values.presets.secretServiceAccount }}
{{- fail "presets.secretServiceAccount is required when an AWS secret provider is used" }}
{{- end }}
{{- if not .Values.presets.db.external.secretProvider.iamRoleARN }}
{{- fail "presets.db.external.secretProvider.iamRoleARN is required when an AWS secret provider is used" }}
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.presets.secretServiceAccount }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.presets.db.external.secretProvider.iamRoleARN }}
{{- end }}
