apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.presets.name }}
  annotations:
  {{- if .Values.presets.commitHash }}
    commitHash: {{ .Values.presets.commitHash }}
  {{- end }}
data:
{{- if .Values.versions.presets }}
  VERSION: {{ .Values.versions.presets | quote }}
{{- end }}
{{- if .Values.presets.PRESETS_PORT_HTTP }}
  PRESETS_PORT_HTTP: {{ .Values.presets.PRESETS_PORT_HTTP | quote }}
{{- end }}
{{- if .Values.presets.DEPLOY_ENVIRONMENT }}
  DEPLOY_ENVIRONMENT: {{ .Values.presets.DEPLOY_ENVIRONMENT | quote }}
{{- end }}