{{- if eq .Values.presets.db.external.secretProvider.provider "aws" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.presets.secretServiceAccount }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.presets.db.external.secretProvider.iamRoleARN }}
{{- end}}