apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.presets.name }}
  labels:
    app: {{ .Values.presets.name }}
spec:
  replicas: {{ .Values.presets.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.presets.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.presets.name }}
      annotations:
        eks.amazonaws.com/compute-type: ec2
        {{ if .Values.presets.commitHash }}commitHash: {{ .Values.presets.commitHash }}{{ end }}
    spec:
      serviceAccountName: {{ .Values.presets.secretServiceAccount }}
      containers:
      - name: {{ .Values.presets.name }}
        image: {{ .Values.presets.registry }}:{{ .Values.versions.presets }}
        {{ if .Values.presets.imagePullPolicy }}imagePullPolicy: {{ .Values.presets.imagePullPolicy }}{{ end }}
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "python cli.py enable-alembic; alembic upgrade head"]
        ports:
        - containerPort: {{ .Values.presets.PRESETS_PORT_HTTP }}
        envFrom:
        - configMapRef:
            name: {{ .Values.presets.name }}
        env:
        - name: PRESETS_BACKEND_DB
          valueFrom:
            secretKeyRef:
              name: {{ .Values.presets.secretName }}
              key: PRESETS_BACKEND_DB
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      - name: {{ .Values.presets.nginx.name }}
        image: {{ .Values.presets.nginx.registry }}:{{ .Values.versions.presets }}
        {{ if .Values.presets.imagePullPolicy }}imagePullPolicy: {{ .Values.presets.imagePullPolicy }}{{ end }}
        ports:
        - containerPort: {{ .Values.presets.nginx.NGINX_PORT_HTTP }}
        envFrom:
        - configMapRef:
            name: {{ .Values.presets.nginx.name }}
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .Values.presets.spcName | quote }}