apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.presets.name }}
  labels:
    app: {{ .Values.presets.name }}
spec:
  replicas: {{ .Values.presets.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.presets.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.presets.name }}
      annotations:
        eks.amazonaws.com/compute-type: ec2
      {{- if .Values.presets.commitHash }}
        commitHash: {{ .Values.presets.commitHash }}
      {{- end }}
    spec:
    {{- if eq .Values.secretProvider "aws" }}
      serviceAccountName: {{ .Values.presets.secretServiceAccount }}
    {{- end }}
      initContainers:
      {{- if and .Values.presets.useCustomConfigurationFiles (eq .Values.presets.customConfigurationLocation "s3")}}
      - name: init-custom-configuration
        image: amazon/aws-cli
        command: ["/bin/sh"]
        args:
          - -c
          - |
            export AWS_ACCESS_KEY_ID={{ .Values.presets.awsAccessKeyId }};
            export AWS_SECRET_ACCESS_KEY={{ .Values.presets.awsAccessKeySecret }};
            AWS_DEFAULT_REGION={{ .Values.presets.awsDefaultRegion }};
            aws s3 cp --recursive --exclude "*/*" s3://{{ .Values.presets.s3bucketName }}{{ .Values.presets.customConfigurationFolderPath }} /presets;
        volumeMounts:
        - mountPath: "/presets/"
          name: {{ .Values.presets.name }}-volume
      {{- end }}
      {{- if and .Values.presets.useCustomWorkspacePresets (eq .Values.presets.customWorkspacePresetLocation "s3")}}
      - name: init-custom-presets
        image: amazon/aws-cli
        command: ["/bin/sh"]
        args:
          - -c
          - |
            export AWS_ACCESS_KEY_ID={{ .Values.presets.awsAccessKeyId }};
            export AWS_SECRET_ACCESS_KEY={{ .Values.presets.awsAccessKeySecret }};
            AWS_DEFAULT_REGION={{ .Values.presets.awsDefaultRegion }};
            aws s3 cp --recursive s3://{{ .Values.presets.customPresetsS3bucketName }}{{ .Values.presets.customPresetsPath }} /custom-presets;
        volumeMounts:
        - mountPath: "/custom-presets/"
          name: {{ .Values.presets.name }}-custom-presets-volume
      {{- end }}
      {{- if .Values.presets.db.useZalandoOperatorDb }}
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', "until nc -z -v -w30 {{ .Values.presets.db.name }} 5432; do echo 'Waiting for database...'; sleep 5; done"]
      {{- end }}
      containers:
      - name: {{ .Values.presets.name }}
        image: {{ .Values.presets.registry }}:{{ default .Chart.AppVersion .Values.versions.presets }}
      {{- if .Values.presets.imagePullPolicy }}
        imagePullPolicy: {{ .Values.presets.imagePullPolicy }}
      {{- end }}
      {{- if .Values.presets.postStartCommand }}
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", {{ .Values.presets.postStartCommand | quote }}]
      {{- end }}
        ports:
        - containerPort: {{ .Values.presets.PRESETS_PORT_HTTP }}
      {{- if .Values.presets.resources }}
        resources: {{ toYaml .Values.presets.resources | nindent 10 }}
      {{- end }}
      {{- if .Values.presets.livenessProbe }}
        livenessProbe: {{ toYaml .Values.presets.livenessProbe | nindent 10 }}
      {{- end }}
      {{- if .Values.presets.readinessProbe }}
        readinessProbe: {{ toYaml .Values.presets.readinessProbe | nindent 10 }}
      {{- end }}
        envFrom:
        - configMapRef:
            name: {{ .Values.presets.name }}
        env:
      {{- if .Values.presets.db.useZalandoOperatorDb }}
        - name: PG_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.presets.db.POSTGRES_USER }}.{{ .Values.presets.db.name }}.credentials.postgresql.acid.zalan.do
              key: password
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.presets.db.POSTGRES_USER }}.{{ .Values.presets.db.name }}.credentials.postgresql.acid.zalan.do
              key: username
      {{- end }}
        - name: PRESETS_BACKEND_DB
        {{- if .Values.presets.db.useZalandoOperatorDb }}
          value: "postgresql://$(PG_USER):$(PG_PASS)@{{ .Values.presets.db.name }}:5432/{{ .Values.presets.db.POSTGRES_DB }}"
        {{- else }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.presets.db_secretName }}
              key: PRESETS_BACKEND_DB
        {{- end }}
        volumeMounts:
      {{- if not .Values.presets.db.useZalandoOperatorDb }}
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      {{- end }}
      {{- if .Values.presets.useCustomWorkspacePresets }}
        - mountPath: "/app/staticpresets"
          name: {{ .Values.presets.name }}-custom-presets-volume
      {{- end }}
      - name: {{ .Values.presets.nginx.name }}
        image: {{ .Values.presets.nginx.registry }}:{{ .Values.presets.nginx.version }}
      {{- if .Values.presets.imagePullPolicy }}
        imagePullPolicy: {{ .Values.presets.imagePullPolicy }}
      {{- end }}
        ports:
        - containerPort: {{ .Values.presets.nginx.NGINX_PORT_HTTP }}
      {{- if .Values.presets.nginx.resources }}
        resources: {{ toYaml .Values.presets.nginx.resources | nindent 10 }}
      {{- end }}
      {{- if .Values.presets.nginx.livenessProbe }}
        livenessProbe: {{ toYaml .Values.presets.nginx.livenessProbe | nindent 10 }}
      {{- end }}
      {{- if .Values.presets.nginx.readinessProbe }}
        readinessProbe: {{ toYaml .Values.presets.nginx.readinessProbe | nindent 10 }}
      {{- end }}
        envFrom:
        - configMapRef:
            name: {{ .Values.presets.nginx.name }}
      {{- if and .Values.presets.useCustomConfigurationFiles }}
        volumeMounts:
        - mountPath: "/nginx.conf"
          subPath: "nginx.conf"
          name: {{ .Values.presets.name }}-volume
      {{- end }}
      {{- if .Values.presets.db.enableDefaultDb }}
      - name: {{ .Values.presets.db.name }}
        image: {{ .Values.presets.db.image }}
        ports:
          - containerPort: {{ .Values.presets.db.port }}
        env:
          - name: POSTGRES_DB
            value: {{ .Values.presets.db.POSTGRES_DB }}
          - name: POSTGRES_USER
            value: {{ .Values.presets.db.POSTGRES_USER }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.presets.db.POSTGRES_PASSWORD }}
      {{- end }}
      volumes:
    {{- if .Values.presets.useCustomConfigurationFiles }}
      - name: {{ .Values.presets.name }}-volume
      {{- if eq .Values.presets.customConfigurationLocation "s3"}}
        emptyDir: {}
      {{- else if eq .Values.presets.customConfigurationLocation "local"}}
        persistentVolumeClaim:
          claimName: {{ .Values.presets.name }}-claim
      {{- end }}
    {{- end }}
    {{- if .Values.presets.useCustomWorkspacePresets}}
      - name: {{ .Values.presets.name }}-custom-presets-volume
      {{- if eq .Values.presets.customWorkspacePresetLocation "s3"}}
        emptyDir: {}
      {{- else if eq .Values.presets.customWorkspacePresetLocation "local"}}
        persistentVolumeClaim:
          claimName: {{ .Values.presets.name }}-custom-presets-claim
      {{- end }}
    {{- end }}
    {{- if not .Values.presets.db.useZalandoOperatorDb }}
      - name: secrets-store-inline
      {{- if .Values.secretProvider }}
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .Values.presets.spcName | quote }}
      {{- else }}
        secret:
          secretName: {{ .Values.presets.db_secretName | quote }}
      {{- end }}
    {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Values.presets.name }}
              topologyKey: topology.kubernetes.io/zone
