{{- if .Values.presets.useSecretProvider }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.presets.secretServiceAccount }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.presets.iamRoleARN }}
{{- end}}