{{- if .Values.presets.useCustomWorkspacePresets }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.presets.name }}-pvc
spec:
  storageClassName: ""
  accessModes:
    - {{ .Values.presets.volumeAccessMode }}
  resources:
    requests:
      storage: {{ .Values.presets.volumeSize }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.presets.name }}-pv
spec:
{{- if eq .Values.presets.volumeType "hostPath" }}
  storageClassName: manual
{{- else if eq .Values.presets.volumeType "csi-s3" }}
  storageClassName: csi-s3
{{- end }}
  capacity:
    storage: {{ .Values.presets.volumeSize }}
  accessModes:
    - {{ .Values.presets.volumeAccessMode }}
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ .Values.presets.name }}-pvc
{{- if eq .Values.presets.volumeType "hostPath" }}
  hostPath:
    path: {{ .Values.presets.volumePath | quote }}
{{- else if eq .Values.presets.volumeType "csi-s3" }}
  csi:
    driver: ru.yandex.s3.csi
    controllerPublishSecretRef:
      name: {{ .Values.presets.csiSecretName }}
      namespace: {{ .Values.presets.csiNamespace }}
    nodePublishSecretRef:
      name: {{ .Values.presets.csiSecretName }}
      namespace: {{ .Values.presets.csiNamespace }}
    nodeStageSecretRef:
      name: {{ .Values.presets.csiSecretName }}
      namespace: {{ .Values.presets.csiNamespace }}
    volumeAttributes:
      capacity: {{ .Values.presets.volumeSize }}
      mounter: geesefs
    volumeHandle: {{ .Values.presets.volumePath }}
{{- end }}
{{- end }}