{{- if .Values.presets.secretProvider }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.presets.spcName }}
spec:
  provider: {{ .Values.presets.secretProvider }}
  parameters:
  {{- if eq .Values.presets.secretProvider "aws" }}
    objects: |
      - objectName: {{ .Values.presets.db_secret | quote }}
        objectType: {{ .Values.presets.db_secretType | quote }}
  {{- else if eq .Values.presets.secretProvider "azure" }}
    objects: |
      array:
        - |
          objectName: {{ .Values.presets.db_secret | quote }}
          objectType: {{ .Values.presets.db_secretType | quote }}
  {{- else if eq .Values.presets.secretProvider "gcp" }}
    secrets: |
      - resourceName: {{ .Values.presets.db_secret | quote }}
        path: {{ .Values.presets.db_secretPath | quote }}
  {{- else if eq .Values.presets.secretProvider "vault" }}
    objects: |
      - objectName: {{ .Values.presets.db_secret | quote }}
        secretPath: {{ .Values.presets.db_secretPath | quote }}
        secretKey: {{ .Values.presets.db_secretKey | quote }}
  {{- end }}
  {{- range $key, $value := .Values.presets.secretProviderParameters }}
    {{ $key }}: {{ $value }}
  {{- end }}
  secretObjects: # Creates kubernetes secret objects
  - data:
    - key: PRESETS_BACKEND_DB
      objectName: {{ .Values.presets.db_secret }}
    secretName: {{ .Values.presets.db_secretName }}
    type: Opaque
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.presets.db_secretName }}
data:
  PRESETS_BACKEND_DB: {{ .Values.presets.db_secret }}
{{- end}}