{{- $dbMode := default "sidecar" .Values.presets.db.mode }}
{{- $external := .Values.presets.db.external }}
{{- $secretProvider := $external.secretProvider }}
{{- if and (eq $dbMode "external") $secretProvider.provider }}
{{- if not $secretProvider.objectName }}
{{- fail "presets.db.external.secretProvider.objectName is required when presets.db.mode is external and a secret provider is configured" }}
{{- end }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $secretProvider.className }}
spec:
  provider: {{ $secretProvider.provider }}
  parameters:
  {{- if or (eq $secretProvider.provider "aws") (eq $secretProvider.provider "azure") }}
    objects: |
      - objectName: {{ $secretProvider.objectName | quote }}
        objectType: {{ $secretProvider.objectType | quote }}
  {{- else if eq $secretProvider.provider "gcp" }}
    secrets: |
      - resourceName: {{ $secretProvider.objectName | quote }}
        path: {{ $secretProvider.path | quote }}
  {{- else if eq $secretProvider.provider "vault" }}
    objects: |
      - objectName: {{ $secretProvider.objectName | quote }}
        secretPath: {{ $secretProvider.path | quote }}
        secretKey: {{ $secretProvider.key | quote }}
  {{- end }}
  {{- range $key, $value := $secretProvider.parameters }}
    {{ $key }}: {{ $value }}
  {{- end }}
  secretObjects: # Creates kubernetes secret objects
  - data:
    - key: {{ $external.secretKey }}
      objectName: {{ $secretProvider.objectName }}
    secretName: {{ $external.secretName }}
    type: Opaque
  {{- else if eq $dbMode "external" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $external.secretName }}
data:
  {{ $external.secretKey }}: {{ $external.encodedConnectionString }}
{{- end}}
