{{- if .Values.presets.useSecretProvider }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.presets.spcName }}
spec:
  provider: aws
  parameters:
    region: eu-north-1
    objects: |
        - objectName: {{ .Values.presets.db_secret | quote }}
          objectType: "secretsmanager"
  secretObjects: # Creates kubernetes secret objects
  - data:
    - key: PRESETS_BACKEND_DB
      objectName: {{ .Values.presets.db_secret }}
    secretName: {{ .Values.presets.db_secretName }}
    type: Opaque
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.presets.db_secretName }}
data:
  PRESETS_BACKEND_DB: {{ .Values.presets.db_secret }}
{{- end}}