apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.presets.name }}
  annotations:
  {{- if .Values.presets.commitHash }}
    commitHash: {{ .Values.presets.commitHash }}
  {{- end }}
data:
  VERSION: {{ .Values.versions.presets | quote }}
  EXTERNALADDRESS: {{ .Values.presets.EXTERNALADDRESS | quote }}
  PRESETS_PORT_HTTP: {{ .Values.presets.PRESETS_PORT_HTTP | quote }}