apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.presets.nginx.name }}
data:
{{- if .Values.presets.nginx.ENABLE_SSL }}
  ENABLE_SSL: {{ .Values.presets.nginx.ENABLE_SSL | quote }}
{{- end }}
{{- if .Values.presets.nginx.OAUTH2_USERINFO }}
  OAUTH2_USERINFO: {{ .Values.presets.nginx.OAUTH2_USERINFO | quote }}
{{- end }}
{{- if .Values.presets.nginx.GEOWEB_USERNAME_CLAIM }}
  GEOWEB_USERNAME_CLAIM: {{ .Values.presets.nginx.GEOWEB_USERNAME_CLAIM | quote }}
{{- end }}
{{- if .Values.presets.nginx.GEOWEB_REQUIRE_READ_PERMISSION }}
  GEOWEB_REQUIRE_READ_PERMISSION: {{ .Values.presets.nginx.GEOWEB_REQUIRE_READ_PERMISSION | quote }}
{{- end }}
{{- if .Values.presets.nginx.GEOWEB_REQUIRE_WRITE_PERMISSION }}
  GEOWEB_REQUIRE_WRITE_PERMISSION: {{ .Values.presets.nginx.GEOWEB_REQUIRE_WRITE_PERMISSION | quote }}
{{- end }}
{{- if .Values.presets.nginx.ALLOW_ANONYMOUS_ACCESS }}
  ALLOW_ANONYMOUS_ACCESS: {{ .Values.presets.nginx.ALLOW_ANONYMOUS_ACCESS | quote }}
{{- end }}
{{- if .Values.presets.nginx.BACKEND_HOST }}
  BACKEND_HOST: {{ .Values.presets.nginx.BACKEND_HOST | quote }}
{{- end }}
{{- if .Values.presets.nginx.NGINX_PORT_HTTP }}
  NGINX_PORT_HTTP: {{ .Values.presets.nginx.NGINX_PORT_HTTP | quote }}
{{- end }}
{{- if .Values.presets.nginx.NGINX_PORT_HTTPS }}
  NGINX_PORT_HTTPS: {{ .Values.presets.nginx.NGINX_PORT_HTTPS | quote }}
{{- end }}