{{- if not .Values.config.plugins.wms.disabled }}
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: {{ .Release.name }}-wms-layer-git-sync
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: {{ .Release.Name }}
#   template:
#     metadata:
#       labels:
#         app: {{ .Release.Name }}
#     spec:
#       securityContext:
#         # Set this to any valid GID, and two things happen:
#         #   1) The volume "content-from-git" is group-owned by this GID.
#         #   2) This GID is added to each container.
#         fsGroup: 0
#       volumes:
#         - name: wms-layers
#           emptyDir: {}
#       containers:
#         - name: git-sync
#           # This container pulls git data and publishes it into volume
#           # "content-from-git".  In that volume you will find a symlink
#           # "current" (see -dest below) which points to a checked-out copy of
#           # the master branch (see -branch) of the repo (see -repo).
#           # NOTE: git-sync already runs as non-root.
#           image: registry.k8s.io/git-sync/git-sync:v4.0.0
#           args:
#             - --repo={{ .Values.config.plugins.wms.gitSync.repository }}
#             - --branch={{ .Values.config.plugins.wms.gitSync.branch }}
#             - --depth=1
#             - --period={{ .Values.config.plugins.wms.gitSync.period }}s
#             - --link=current
#             - --root=/wms-layers
#           volumeMounts:
#             - name: wms-layers
#               mountPath: /wms-layers
{{- end }}