{{- if .Values.gui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "smartmet-verify.componentFullname" (list . "gui") }}
  labels:
    {{- include "smartmet-verify.componentLabels" (list . "gui") | nindent 4 }}
spec:
  type: {{ .Values.gui.service.type }}
  selector:
    {{- include "smartmet-verify.componentSelectorLabels" (list . "gui") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.gui.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}
