apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.opmet.spcName }}
spec:
  provider: aws
  parameters:
    region: eu-north-1
    objects: |
        - objectName: {{ .Values.opmet.db_secret | quote }}
          objectType: "secretsmanager"
  secretObjects: # Creates kubernetes secret objects
  - data:
    - key: OPMET_BACKEND_DB
      objectName: {{ .Values.opmet.db_secret }}
    secretName: {{ .Values.opmet.secretName }}
    type: Opaque