apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.opmet.name }}
spec:
  selector:
    app: {{ .Values.opmet.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.opmet.svcPort }}
      targetPort: {{ .Values.opmet.nginx.NGINX_PORT_HTTP }}