apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: imagestreams.image.openshift.io
spec:
  group: image.openshift.io
  scope: Namespaced
  names:
    plural: imagestreams
    singular: imagestream
    kind: ImageStream
    shortNames: [is]
  versions:
  - name: v1
    served: true
    storage: true
    # Intentionally an empty schema, just to make the Kind based linter happy
    schema:
      openAPIV3Schema:
        type: object
