apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: templates.template.openshift.io
spec:
  group: template.openshift.io
  scope: Namespaced
  names:
    plural: templates
    singular: template
    kind: Template
  versions:
  - name: v1
    served: true
    storage: true
    # Intentionally an empty schema, just to make the Kind based linter happy
    schema:
      openAPIV3Schema:
        type: object
