versions:
  presets: "1.4.1"

presets:
  name: presets
  registry: registry.gitlab.com/opengeoweb/backend-services/presets-backend/presets-backend
  path: /presets/(.*)
  svcPort: 80
  replicas: 1
  EXTERNALADDRESS: 0.0.0.0:80
  PRESETS_PORT_HTTP: 8080
  secretName: presets-db
  spcName: presets-spc
  secretServiceAccount: presets-service-account
  nginx:
    name: nginx
    registry: registry.gitlab.com/opengeoweb/backend-services/presets-backend/nginx-presets-backend
    PRESETS_ENABLE_SSL: "FALSE"
    OAUTH2_USERINFO: https://gitlab.com/oauth/userinfo
    PRESETS_BACKEND_HOST: 0.0.0.0:8080
    NGINX_PORT_HTTP: 80
ingress:
  name: nginx-ingress-controller # Sync with nginx-ingress-controller/values.yaml