versions:
  presets: "3.0.0"

presets:
  name: presets
  registry: registry.gitlab.com/opengeoweb/backend-services/presets-backend/presets-backend
  path: /presets/(.*)
  svcPort: 80
  replicas: 1
  EXTERNALADDRESS: 0.0.0.0:80
  PRESETS_PORT_HTTP: 8080
  db_secretName: presets-db
  db_secretType: secretsmanager
  spcName: presets-spc
  secretServiceAccount: presets-service-account
  nginx:
    name: nginx
    registry: registry.gitlab.com/opengeoweb/backend-services/presets-backend/nginx-presets-backend
    PRESETS_ENABLE_SSL: "FALSE"
    OAUTH2_USERINFO: https://gitlab.com/oauth/userinfo
    PRESETS_BACKEND_HOST: 0.0.0.0:8080
    NGINX_PORT_HTTP: 80
  useCustomWorkspacePresets: false
  volumeAccessMode: ReadOnlyMany
  volumeSize: 100Mi
  volumeType: hostPath
  volumePath: /mnt/presets
  csiNamespace: kube-system
  csiSecretName: csi-s3-secret

ingress:
  name: nginx-ingress-controller # Sync with nginx-ingress-controller/values.yaml
