versions:
  presets:

presets:
  name: presets
  registry: registry.gitlab.com/opengeoweb/backend-services/presets-backend/presets-backend
  path: /presets/(.*)
  svcPort: 80
  replicas: 1
  PRESETS_PORT_HTTP: 8080
  DEPLOY_ENVIRONMENT: open
  postStartCommand: bin/admin.sh
  db_secret: cG9zdGdyZXNxbDovL2dlb3dlYjpwb3N0Z3Jlc0Bsb2NhbGhvc3Q6NTQzMi9wcmVzZXRz
  db_secretName: presets-db
  db_secretType: secretsmanager
  spcName: presets-spc
  secretServiceAccount: presets-service-account
  resources:
    requests:
      memory: "250Mi"
      cpu: "50m"
    limits:
      memory: "350Mi"
      cpu: "1"
  livenessProbe:
    httpGet:
      path: /healthcheck
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 5
    failureThreshold: 5
  readinessProbe:
    httpGet:
      path: /healthcheck?readiness=true
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 5
    failureThreshold: 1
  nginx:
    name: nginx
    registry: registry.gitlab.com/opengeoweb/backend-services/auth-backend/auth-backend
    version: "v0.1.0"
    ENABLE_SSL: "FALSE"
    BACKEND_HOST: 0.0.0.0:8080
    NGINX_PORT_HTTP: 80
    NGINX_PORT_HTTPS: 443
    resources:
      requests:
        memory: "10Mi"
        cpu: "10m"
      limits:
        memory: "100Mi"
        cpu: "100m"
    livenessProbe:
      httpGet:
        path: /health_check
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 5
    readinessProbe:
      httpGet:
        path: /health_check?readiness=true
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 1
  db:
    enableDefaultDb: true
    useZalandoOperatorDb: false
    name: presets-db
    image: postgres
    port: 5432
    POSTGRES_DB: presets
    POSTGRES_USER: geoweb
    POSTGRES_PASSWORD: postgres
    POSTGRES_VERSION: 15
    numberOfInstances: 1
    instanceSize: 100Mi
    zalandoTeamId: geoweb
    enableLogicalBackup: true
    cleanInstall: true
    backupTimestamp: "2030-01-01T00:00:00+00:00"
  useCustomConfigurationFiles: false
  customConfigurationLocation: local
  useCustomWorkspacePresets: false
  customWorkspacePresetLocation: local
  volumeAccessMode: ReadOnlyMany
  volumeSize: 100Mi

ingress:
  name: nginx-ingress-controller
  ingressClassName: nginx
