versions:
  presets: "3.5.2"

presets:
  name: presets
  registry: registry.gitlab.com/opengeoweb/backend-services/presets-backend/presets-backend
  path: /presets/(.*)
  svcPort: 80
  replicas: 1
  EXTERNALADDRESS: 0.0.0.0:80
  PRESETS_PORT_HTTP: 8080
  DEPLOY_ENVIRONMENT: open
  postStartCommand: bin/admin.sh
  db_secretName: presets-db
  db_secretType: secretsmanager
  spcName: presets-spc
  secretServiceAccount: presets-service-account
  resources:
    requests:
      memory: "250Mi"
      cpu: "50m"
    limits:
      memory: "350Mi"
      cpu: "1"
  nginx:
    name: nginx
    registry: registry.gitlab.com/opengeoweb/backend-services/presets-backend/nginx-presets-backend
    PRESETS_ENABLE_SSL: "FALSE"
    PRESETS_BACKEND_HOST: 0.0.0.0:8080
    NGINX_PORT_HTTP: 80
    resources:
      requests:
        memory: "10Mi"
        cpu: "10m"
      limits:
        memory: "100Mi"
        cpu: "100m"
  useCustomWorkspacePresets: false
  customWorkspacePresetLocation: local
  volumeAccessMode: ReadOnlyMany
  volumeSize: 100Mi

ingress:
  name: nginx-ingress-controller
  ingressClassName: nginx
