{{- if .Values.nodeports }}
{{- range $name, $nodeport := .Values.nodeports }}
{{- if $nodeport.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-nodeport
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
  - name: {{ $name }}-service-port
    nodePort: {{ $nodeport.apiPort }}
    port: {{ $nodeport.servicePort }}
    protocol: TCP
    targetPort: {{ $nodeport.targetPodPort }}
  selector:
    {{- if $nodeport.selector }}
    app: {{ $nodeport.selector.app }}
    component: {{ $nodeport.selector.component }}
    release: {{ $nodeport.selector.release }}
    {{- else }}
    app.kubernetes.io/instance: {{ $.Release.Namespace }}
    {{- end }}
  type: NodePort
{{- end }}
{{- end }}
{{- end }}